import { useState, useEffect, useCallback } from 'react';
import { Button } from '@/components/ui/button';
import { PageHeader, SearchBar, DataCard, EmptyState } from '@/components/shared/PageComponents';
import { ListActionBar } from '@/components/shared/ListActionBar';
import { Edit, Trash2, Video, Loader2 } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { GravacaoFormModal } from '@/components/producao/GravacaoFormModal';
import { Badge } from '@/components/ui/badge';
import { SortableTable, Column } from '@/components/shared/SortableTable';
import { useLanguage } from '@/contexts/LanguageContext';
import { usePermissions } from '@/hooks/usePermissions';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';

// Legacy format used by the form modal and other components
export interface Gravacao {
  id: string;
  codigo: string;
  codigoExterno: string;
  nome: string;
  unidadeNegocio: string;
  centroLucro: string;
  classificacao: string;
  tipoConteudo: string;
  descricao: string;
  status: string;
  dataPrevista: string;
  dataCadastro: string;
  usuarioCadastro: string;
  conteudoId?: string;
}

// Database format from Supabase
interface GravacaoDB {
  id: string;
  codigo: string;
  codigo_externo: string | null;
  nome: string;
  unidade_negocio_id: string | null;
  centro_lucro_id: string | null;
  classificacao_id: string | null;
  tipo_conteudo_id: string | null;
  descricao: string | null;
  status_id: string | null;
  data_prevista: string | null;
  created_at: string | null;
  created_by: string | null;
  conteudo_id: string | null;
  // Joined fields
  unidade_negocio?: { nome: string } | null;
  centro_lucro?: { nome: string } | null;
  classificacao?: { nome: string } | null;
  tipo_conteudo?: { nome: string } | null;
  status_gravacao?: { nome: string; cor: string } | null;
}

// Generate placeholder code for new recordings
// The actual code (YYYYNNNNN format, e.g., 202600001) is generated by the database trigger
export const generateCodigoGravacao = (): string => {
  const currentYear = new Date().getFullYear();
  return `${currentYear}XXXXX`;
};

const GravacaoList = () => {
  const { toast } = useToast();
  const { t } = useLanguage();
  const { user, session } = useAuth();
  const { canIncluir, canAlterar, canExcluir } = usePermissions();
  
  // Permissões de ação
  const podeIncluir = canIncluir('Produção', 'Gravação');
  const podeAlterar = canAlterar('Produção', 'Gravação');
  const podeExcluir = canExcluir('Produção', 'Gravação');
  
  const [search, setSearch] = useState('');
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingItem, setEditingItem] = useState<Gravacao | null>(null);
  const [items, setItems] = useState<GravacaoDB[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  // Fetch data from Supabase
  const fetchData = useCallback(async () => {
    if (!session) {
      setIsLoading(false);
      return;
    }

    setIsLoading(true);
    try {
      const { data, error } = await supabase
        .from('gravacoes')
        .select(`
          *,
          unidade_negocio:unidade_negocio_id(nome),
          centro_lucro:centro_lucro_id(nome),
          classificacao:classificacao_id(nome),
          tipo_conteudo:tipo_conteudo_id(nome),
          status_gravacao:status_id(nome, cor)
        `)
        .order('created_at', { ascending: false });

      if (error) {
        throw error;
      }

      setItems(data || []);
    } catch (err) {
      console.error('Error fetching gravacoes:', err);
      toast({
        title: 'Erro',
        description: `Erro ao carregar gravações: ${(err as Error).message}`,
        variant: 'destructive',
      });
    } finally {
      setIsLoading(false);
    }
  }, [session, toast]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  // Convert DB format to legacy format for form modal
  const toFormFormat = (item: GravacaoDB): Gravacao => ({
    id: item.id,
    codigo: item.codigo,
    codigoExterno: item.codigo_externo || '',
    nome: item.nome,
    unidadeNegocio: item.unidade_negocio?.nome || '',
    centroLucro: item.centro_lucro?.nome || '',
    classificacao: item.classificacao?.nome || '',
    tipoConteudo: item.tipo_conteudo?.nome || '',
    descricao: item.descricao || '',
    status: item.status_gravacao?.nome || '',
    dataPrevista: item.data_prevista || '',
    dataCadastro: item.created_at ? new Date(item.created_at).toLocaleDateString('pt-BR') : '',
    usuarioCadastro: user?.nome || '',
    conteudoId: item.conteudo_id || undefined,
  });

  const handleSave = async (data: Gravacao) => {
    try {
      // Buscar IDs das referências pelo nome
      const [unidadeRes, centroRes, classificacaoRes, tipoRes, statusRes] = await Promise.all([
        data.unidadeNegocio ? supabase.from('unidades_negocio').select('id').eq('nome', data.unidadeNegocio).single() : Promise.resolve({ data: null }),
        data.centroLucro ? supabase.from('centros_lucro').select('id').eq('nome', data.centroLucro).single() : Promise.resolve({ data: null }),
        data.classificacao ? supabase.from('classificacoes').select('id').eq('nome', data.classificacao).single() : Promise.resolve({ data: null }),
        data.tipoConteudo ? supabase.from('tipos_gravacao').select('id').eq('nome', data.tipoConteudo).single() : Promise.resolve({ data: null }),
        data.status ? supabase.from('status_gravacao').select('id').eq('nome', data.status).single() : Promise.resolve({ data: null }),
      ]);

      // Converter data de dd/MM/yyyy para yyyy-MM-dd
      let dataPrevistaFormatted: string | null = null;
      if (data.dataPrevista) {
        const parts = data.dataPrevista.split('/');
        if (parts.length === 3) {
          dataPrevistaFormatted = `${parts[2]}-${parts[1]}-${parts[0]}`;
        }
      }

      const recordData = {
        nome: data.nome,
        codigo_externo: data.codigoExterno || null,
        descricao: data.descricao || null,
        unidade_negocio_id: unidadeRes.data?.id || null,
        centro_lucro_id: centroRes.data?.id || null,
        classificacao_id: classificacaoRes.data?.id || null,
        tipo_conteudo_id: tipoRes.data?.id || null,
        status_id: statusRes.data?.id || null,
        data_prevista: dataPrevistaFormatted,
        conteudo_id: data.conteudoId || null,
        created_by: user?.id || null,
      };

      if (editingItem) {
        // Update existing record
        const { error } = await supabase
          .from('gravacoes')
          .update(recordData)
          .eq('id', data.id);

        if (error) throw error;
        toast({ title: t('common.success'), description: t('recordings.edit') + '!' });
      } else {
        // Insert new record - código será gerado pelo trigger no DB
        const { error } = await supabase
          .from('gravacoes')
          .insert({
            ...recordData,
            codigo: data.codigo, // Código temporário, será substituído pelo trigger se existir
          });

        if (error) throw error;
        toast({ title: t('common.success'), description: t('recordings.new') + '!' });
      }
      
      await fetchData();
      setEditingItem(null);
    } catch (err) {
      console.error('Error saving gravacao:', err);
      toast({
        title: 'Erro',
        description: `Erro ao salvar: ${(err as Error).message}`,
        variant: 'destructive',
      });
    }
  };

  const handleDelete = async (id: string) => {
    if (confirm(t('common.confirm.delete'))) {
      try {
        const { error } = await supabase
          .from('gravacoes')
          .delete()
          .eq('id', id);

        if (error) throw error;

        toast({ title: t('common.deleted'), description: t('recordings.title') + '!' });
        await fetchData();
      } catch (err) {
        console.error('Error deleting gravacao:', err);
        toast({
          title: 'Erro',
          description: `Erro ao excluir: ${(err as Error).message}`,
          variant: 'destructive',
        });
      }
    }
  };

  const filteredItems = items.filter(
    (item) =>
      item.nome?.toLowerCase().includes(search.toLowerCase()) ||
      item.codigo?.toLowerCase().includes(search.toLowerCase()) ||
      (item.codigo_externo || '').toLowerCase().includes(search.toLowerCase())
  );

  const columns: Column<GravacaoDB>[] = [
    {
      key: 'codigo',
      label: t('common.code'),
      className: 'w-32',
      render: (item) => (
        <span className="font-mono text-sm font-medium text-primary">{item.codigo || '-'}</span>
      ),
    },
    {
      key: 'nome',
      label: t('common.name'),
      render: (item) => <span className="font-medium">{item.nome}</span>,
    },
    {
      key: 'tipo_conteudo_id',
      label: t('common.type'),
      render: (item) => item.tipo_conteudo?.nome || '-',
    },
    {
      key: 'classificacao_id',
      label: t('content.classification'),
      render: (item) => item.classificacao?.nome || '-',
    },
    {
      key: 'status_id',
      label: t('common.status'),
      render: (item) => {
        const cor = item.status_gravacao?.cor;
        return (
          <Badge 
            style={cor ? { backgroundColor: cor } : undefined}
            className={cor ? 'text-white' : 'bg-muted text-muted-foreground'}
          >
            {item.status_gravacao?.nome || t('common.none')}
          </Badge>
        );
      },
    },
    {
      key: 'created_at',
      label: t('common.registrationDate'),
      className: 'w-32',
      render: (item) => item.created_at ? new Date(item.created_at).toLocaleDateString('pt-BR') : '-',
    },
    {
      key: 'acoes',
      label: t('common.actions'),
      className: 'w-24 text-right',
      sortable: false,
      render: (item) => (
        <div className="flex justify-end gap-1">
          {podeAlterar && (
            <Button
              size="icon"
              variant="ghost"
              onClick={(e) => {
                e.stopPropagation();
                setEditingItem(toFormFormat(item));
                setIsModalOpen(true);
              }}
            >
              <Edit className="w-4 h-4" />
            </Button>
          )}
          {podeExcluir && (
            <Button
              size="icon"
              variant="ghost"
              onClick={(e) => {
                e.stopPropagation();
                handleDelete(item.id);
              }}
              className="text-destructive hover:text-destructive"
            >
              <Trash2 className="w-4 h-4" />
            </Button>
          )}
        </div>
      ),
    },
  ];

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <div>
      <PageHeader
        title={t('recordings.title')}
        description={t('recordings.description')}
        onAdd={podeIncluir ? () => {
          setEditingItem(null);
          setIsModalOpen(true);
        } : undefined}
        addLabel={t('recordings.new')}
      />

      <ListActionBar>
        <SearchBar value={search} onChange={setSearch} placeholder={t('common.search')} />
      </ListActionBar>

      <DataCard>
        {filteredItems.length === 0 ? (
          <EmptyState
            title={t('recordings.empty')}
            description={t('recordings.emptyDescription')}
            icon={Video}
            onAction={() => setIsModalOpen(true)}
            actionLabel={t('recordings.new')}
          />
        ) : (
          <SortableTable
            data={filteredItems}
            columns={columns}
            getRowKey={(item) => item.id}
            storageKey="kreato_gravacoes_table"
          />
        )}
      </DataCard>

      <GravacaoFormModal
        isOpen={isModalOpen}
        onClose={() => {
          setIsModalOpen(false);
          setEditingItem(null);
        }}
        onSave={handleSave}
        data={editingItem}
      />
    </div>
  );
};

export default GravacaoList;
