// Lista completa de moedas mundiais
export const CURRENCIES = [
  { code: 'AED', name: 'Dirham dos Emirados Árabes Unidos', symbol: 'د.إ' },
  { code: 'AFN', name: 'Afegane', symbol: '؋' },
  { code: 'ALL', name: 'Lek albanês', symbol: 'L' },
  { code: 'AMD', name: 'Dram armênio', symbol: '֏' },
  { code: 'ANG', name: 'Florim das Antilhas Holandesas', symbol: 'ƒ' },
  { code: 'AOA', name: 'Kwanza angolano', symbol: 'Kz' },
  { code: 'ARS', name: 'Peso argentino', symbol: '$' },
  { code: 'AUD', name: 'Dólar australiano', symbol: 'A$' },
  { code: 'AWG', name: 'Florim de Aruba', symbol: 'ƒ' },
  { code: 'AZN', name: 'Manat azerbaijano', symbol: '₼' },
  { code: 'BAM', name: 'Marco conversível da Bósnia e Herzegovina', symbol: 'KM' },
  { code: 'BBD', name: 'Dólar de Barbados', symbol: 'Bds$' },
  { code: 'BDT', name: 'Taka de Bangladesh', symbol: '৳' },
  { code: 'BGN', name: 'Lev búlgaro', symbol: 'лв' },
  { code: 'BHD', name: 'Dinar do Bahrein', symbol: '.د.ب' },
  { code: 'BIF', name: 'Franco do Burundi', symbol: 'FBu' },
  { code: 'BMD', name: 'Dólar das Bermudas', symbol: '$' },
  { code: 'BND', name: 'Dólar de Brunei', symbol: 'B$' },
  { code: 'BOB', name: 'Boliviano', symbol: 'Bs.' },
  { code: 'BRL', name: 'Real brasileiro', symbol: 'R$' },
  { code: 'BSD', name: 'Dólar das Bahamas', symbol: 'B$' },
  { code: 'BTN', name: 'Ngultrum do Butão', symbol: 'Nu.' },
  { code: 'BWP', name: 'Pula de Botswana', symbol: 'P' },
  { code: 'BYN', name: 'Rublo bielorrusso', symbol: 'Br' },
  { code: 'BZD', name: 'Dólar de Belize', symbol: 'BZ$' },
  { code: 'CAD', name: 'Dólar canadense', symbol: 'C$' },
  { code: 'CDF', name: 'Franco congolês', symbol: 'FC' },
  { code: 'CHF', name: 'Franco suíço', symbol: 'CHF' },
  { code: 'CLP', name: 'Peso chileno', symbol: '$' },
  { code: 'CNY', name: 'Yuan chinês', symbol: '¥' },
  { code: 'COP', name: 'Peso colombiano', symbol: '$' },
  { code: 'CRC', name: 'Colón costa-riquenho', symbol: '₡' },
  { code: 'CUP', name: 'Peso cubano', symbol: '₱' },
  { code: 'CVE', name: 'Escudo cabo-verdiano', symbol: '$' },
  { code: 'CZK', name: 'Coroa checa', symbol: 'Kč' },
  { code: 'DJF', name: 'Franco do Djibuti', symbol: 'Fdj' },
  { code: 'DKK', name: 'Coroa dinamarquesa', symbol: 'kr' },
  { code: 'DOP', name: 'Peso dominicano', symbol: 'RD$' },
  { code: 'DZD', name: 'Dinar argelino', symbol: 'د.ج' },
  { code: 'EGP', name: 'Libra egípcia', symbol: 'E£' },
  { code: 'ERN', name: 'Nakfa da Eritreia', symbol: 'Nfk' },
  { code: 'ETB', name: 'Birr etíope', symbol: 'Br' },
  { code: 'EUR', name: 'Euro', symbol: '€' },
  { code: 'FJD', name: 'Dólar de Fiji', symbol: 'FJ$' },
  { code: 'FKP', name: 'Libra das Ilhas Malvinas', symbol: '£' },
  { code: 'GBP', name: 'Libra esterlina', symbol: '£' },
  { code: 'GEL', name: 'Lari georgiano', symbol: '₾' },
  { code: 'GHS', name: 'Cedi ganês', symbol: 'GH₵' },
  { code: 'GIP', name: 'Libra de Gibraltar', symbol: '£' },
  { code: 'GMD', name: 'Dalasi da Gâmbia', symbol: 'D' },
  { code: 'GNF', name: 'Franco guineense', symbol: 'FG' },
  { code: 'GTQ', name: 'Quetzal guatemalteco', symbol: 'Q' },
  { code: 'GYD', name: 'Dólar da Guiana', symbol: 'G$' },
  { code: 'HKD', name: 'Dólar de Hong Kong', symbol: 'HK$' },
  { code: 'HNL', name: 'Lempira hondurenha', symbol: 'L' },
  { code: 'HRK', name: 'Kuna croata', symbol: 'kn' },
  { code: 'HTG', name: 'Gourde haitiano', symbol: 'G' },
  { code: 'HUF', name: 'Florim húngaro', symbol: 'Ft' },
  { code: 'IDR', name: 'Rupia indonésia', symbol: 'Rp' },
  { code: 'ILS', name: 'Novo shekel israelense', symbol: '₪' },
  { code: 'INR', name: 'Rupia indiana', symbol: '₹' },
  { code: 'IQD', name: 'Dinar iraquiano', symbol: 'ع.د' },
  { code: 'IRR', name: 'Rial iraniano', symbol: '﷼' },
  { code: 'ISK', name: 'Coroa islandesa', symbol: 'kr' },
  { code: 'JMD', name: 'Dólar jamaicano', symbol: 'J$' },
  { code: 'JOD', name: 'Dinar jordaniano', symbol: 'د.ا' },
  { code: 'JPY', name: 'Iene japonês', symbol: '¥' },
  { code: 'KES', name: 'Xelim queniano', symbol: 'KSh' },
  { code: 'KGS', name: 'Som quirguiz', symbol: 'лв' },
  { code: 'KHR', name: 'Riel cambojano', symbol: '៛' },
  { code: 'KMF', name: 'Franco comorense', symbol: 'CF' },
  { code: 'KPW', name: 'Won norte-coreano', symbol: '₩' },
  { code: 'KRW', name: 'Won sul-coreano', symbol: '₩' },
  { code: 'KWD', name: 'Dinar kuwaitiano', symbol: 'د.ك' },
  { code: 'KYD', name: 'Dólar das Ilhas Cayman', symbol: 'CI$' },
  { code: 'KZT', name: 'Tenge cazaque', symbol: '₸' },
  { code: 'LAK', name: 'Kip laosiano', symbol: '₭' },
  { code: 'LBP', name: 'Libra libanesa', symbol: 'ل.ل' },
  { code: 'LKR', name: 'Rupia do Sri Lanka', symbol: 'Rs' },
  { code: 'LRD', name: 'Dólar liberiano', symbol: 'L$' },
  { code: 'LSL', name: 'Loti do Lesoto', symbol: 'L' },
  { code: 'LYD', name: 'Dinar líbio', symbol: 'ل.د' },
  { code: 'MAD', name: 'Dirham marroquino', symbol: 'د.م.' },
  { code: 'MDL', name: 'Leu moldavo', symbol: 'L' },
  { code: 'MGA', name: 'Ariary malgaxe', symbol: 'Ar' },
  { code: 'MKD', name: 'Dinar macedônio', symbol: 'ден' },
  { code: 'MMK', name: 'Kyat birmanês', symbol: 'K' },
  { code: 'MNT', name: 'Tugrik mongol', symbol: '₮' },
  { code: 'MOP', name: 'Pataca de Macau', symbol: 'MOP$' },
  { code: 'MRU', name: 'Ouguiya mauritana', symbol: 'UM' },
  { code: 'MUR', name: 'Rupia mauriciana', symbol: '₨' },
  { code: 'MVR', name: 'Rufia maldiva', symbol: 'Rf' },
  { code: 'MWK', name: 'Kwacha malauiano', symbol: 'MK' },
  { code: 'MXN', name: 'Peso mexicano', symbol: '$' },
  { code: 'MYR', name: 'Ringgit malaio', symbol: 'RM' },
  { code: 'MZN', name: 'Metical moçambicano', symbol: 'MT' },
  { code: 'NAD', name: 'Dólar namibiano', symbol: 'N$' },
  { code: 'NGN', name: 'Naira nigeriana', symbol: '₦' },
  { code: 'NIO', name: 'Córdoba nicaraguense', symbol: 'C$' },
  { code: 'NOK', name: 'Coroa norueguesa', symbol: 'kr' },
  { code: 'NPR', name: 'Rupia nepalesa', symbol: '₨' },
  { code: 'NZD', name: 'Dólar neozelandês', symbol: 'NZ$' },
  { code: 'OMR', name: 'Rial omanense', symbol: 'ر.ع.' },
  { code: 'PAB', name: 'Balboa panamenho', symbol: 'B/.' },
  { code: 'PEN', name: 'Sol peruano', symbol: 'S/' },
  { code: 'PGK', name: 'Kina papua-nova-guineense', symbol: 'K' },
  { code: 'PHP', name: 'Peso filipino', symbol: '₱' },
  { code: 'PKR', name: 'Rupia paquistanesa', symbol: '₨' },
  { code: 'PLN', name: 'Zloty polonês', symbol: 'zł' },
  { code: 'PYG', name: 'Guarani paraguaio', symbol: '₲' },
  { code: 'QAR', name: 'Rial catarense', symbol: 'ر.ق' },
  { code: 'RON', name: 'Leu romeno', symbol: 'lei' },
  { code: 'RSD', name: 'Dinar sérvio', symbol: 'дин.' },
  { code: 'RUB', name: 'Rublo russo', symbol: '₽' },
  { code: 'RWF', name: 'Franco ruandês', symbol: 'FRw' },
  { code: 'SAR', name: 'Rial saudita', symbol: 'ر.س' },
  { code: 'SBD', name: 'Dólar das Ilhas Salomão', symbol: 'SI$' },
  { code: 'SCR', name: 'Rupia seichelense', symbol: '₨' },
  { code: 'SDG', name: 'Libra sudanesa', symbol: 'ج.س.' },
  { code: 'SEK', name: 'Coroa sueca', symbol: 'kr' },
  { code: 'SGD', name: 'Dólar de Singapura', symbol: 'S$' },
  { code: 'SHP', name: 'Libra de Santa Helena', symbol: '£' },
  { code: 'SLL', name: 'Leone serra-leonense', symbol: 'Le' },
  { code: 'SOS', name: 'Xelim somali', symbol: 'S' },
  { code: 'SRD', name: 'Dólar surinamês', symbol: '$' },
  { code: 'SSP', name: 'Libra sul-sudanesa', symbol: '£' },
  { code: 'STN', name: 'Dobra são-tomense', symbol: 'Db' },
  { code: 'SYP', name: 'Libra síria', symbol: '£' },
  { code: 'SZL', name: 'Lilangeni da Essuatíni', symbol: 'L' },
  { code: 'THB', name: 'Baht tailandês', symbol: '฿' },
  { code: 'TJS', name: 'Somoni tajique', symbol: 'SM' },
  { code: 'TMT', name: 'Manat turcomeno', symbol: 'T' },
  { code: 'TND', name: 'Dinar tunisiano', symbol: 'د.ت' },
  { code: 'TOP', name: 'Paʻanga tonganesa', symbol: 'T$' },
  { code: 'TRY', name: 'Lira turca', symbol: '₺' },
  { code: 'TTD', name: 'Dólar de Trinidad e Tobago', symbol: 'TT$' },
  { code: 'TWD', name: 'Novo dólar taiwanês', symbol: 'NT$' },
  { code: 'TZS', name: 'Xelim tanzaniano', symbol: 'TSh' },
  { code: 'UAH', name: 'Hryvnia ucraniana', symbol: '₴' },
  { code: 'UGX', name: 'Xelim ugandense', symbol: 'USh' },
  { code: 'USD', name: 'Dólar americano', symbol: '$' },
  { code: 'UYU', name: 'Peso uruguaio', symbol: '$U' },
  { code: 'UZS', name: 'Som uzbeque', symbol: 'лв' },
  { code: 'VES', name: 'Bolívar venezuelano', symbol: 'Bs.' },
  { code: 'VND', name: 'Dong vietnamita', symbol: '₫' },
  { code: 'VUV', name: 'Vatu vanuatuense', symbol: 'VT' },
  { code: 'WST', name: 'Tala samoana', symbol: 'WS$' },
  { code: 'XAF', name: 'Franco CFA da África Central', symbol: 'FCFA' },
  { code: 'XCD', name: 'Dólar do Caribe Oriental', symbol: 'EC$' },
  { code: 'XOF', name: 'Franco CFA da África Ocidental', symbol: 'CFA' },
  { code: 'XPF', name: 'Franco CFP', symbol: '₣' },
  { code: 'YER', name: 'Rial iemenita', symbol: '﷼' },
  { code: 'ZAR', name: 'Rand sul-africano', symbol: 'R' },
  { code: 'ZMW', name: 'Kwacha zambiano', symbol: 'ZK' },
  { code: 'ZWL', name: 'Dólar zimbabuano', symbol: 'Z$' },
];

// Função para formatar valor com base na moeda
export const formatCurrency = (value: number, currencyCode: string = 'BRL'): string => {
  try {
    return new Intl.NumberFormat(getLocaleForCurrency(currencyCode), {
      style: 'currency',
      currency: currencyCode,
    }).format(value);
  } catch {
    // Fallback para BRL se a moeda não for suportada
    return new Intl.NumberFormat('pt-BR', {
      style: 'currency',
      currency: 'BRL',
    }).format(value);
  }
};

// Mapeamento de moeda para locale mais apropriado
const getLocaleForCurrency = (currencyCode: string): string => {
  const localeMap: Record<string, string> = {
    BRL: 'pt-BR',
    USD: 'en-US',
    EUR: 'de-DE',
    GBP: 'en-GB',
    JPY: 'ja-JP',
    CNY: 'zh-CN',
    ARS: 'es-AR',
    MXN: 'es-MX',
    CLP: 'es-CL',
    COP: 'es-CO',
    PEN: 'es-PE',
    UYU: 'es-UY',
    AUD: 'en-AU',
    CAD: 'en-CA',
    CHF: 'de-CH',
    INR: 'hi-IN',
    KRW: 'ko-KR',
    RUB: 'ru-RU',
    ZAR: 'en-ZA',
    TRY: 'tr-TR',
    PLN: 'pl-PL',
    SEK: 'sv-SE',
    NOK: 'nb-NO',
    DKK: 'da-DK',
    NZD: 'en-NZ',
    SGD: 'en-SG',
    HKD: 'zh-HK',
    THB: 'th-TH',
    MYR: 'ms-MY',
    IDR: 'id-ID',
    PHP: 'en-PH',
    VND: 'vi-VN',
    EGP: 'ar-EG',
    SAR: 'ar-SA',
    AED: 'ar-AE',
    ILS: 'he-IL',
    CZK: 'cs-CZ',
    HUF: 'hu-HU',
    RON: 'ro-RO',
    BGN: 'bg-BG',
    HRK: 'hr-HR',
    UAH: 'uk-UA',
  };

  return localeMap[currencyCode] || 'en-US';
};

// Obter moeda por código
export const getCurrencyByCode = (code: string) => {
  return CURRENCIES.find(c => c.code === code) || CURRENCIES.find(c => c.code === 'BRL');
};
