import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'pt' | 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  formatCurrency: (value: number) => string;
  formatDate: (date: Date | string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations
const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Login
    'login.welcome': 'Bem-vindo ao Kreato',
    'login.subtitle': 'Sistema de Gestão de Produção',
    'login.user': 'Usuário',
    'login.user.placeholder': 'Digite seu usuário',
    'login.password': 'Senha',
    'login.password.placeholder': 'Digite sua senha',
    'login.submit': 'Entrar no Sistema',
    'login.loading': 'Entrando...',
    'login.error': 'Usuário ou senha inválidos',
    'login.hint': 'Acesso inicial: Admin / kreato',
    
    // Common
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.add': 'Adicionar',
    'common.new': 'Novo',
    'common.search': 'Pesquisar...',
    'common.actions': 'Ações',
    'common.yes': 'Sim',
    'common.no': 'Não',
    'common.loading': 'Carregando...',
    'common.success': 'Sucesso',
    'common.error': 'Erro',
    'common.deleted': 'Excluído',
    'common.confirm.delete': 'Deseja realmente excluir?',
    'common.noResults': 'Nenhum resultado encontrado',
    'common.code': 'Código',
    'common.externalCode': 'Código Externo',
    'common.name': 'Nome',
    'common.description': 'Descrição',
    'common.status': 'Status',
    'common.date': 'Data',
    'common.user': 'Usuário',
    'common.registrationDate': 'Data de Cadastro',
    'common.registrationUser': 'Usuário de Cadastro',
    'common.total': 'Total',
    'common.quantity': 'Quantidade',
    'common.value': 'Valor',
    'common.observations': 'Observações',
    'common.image': 'Imagem',
    'common.logo': 'Logotipo',
    'common.upload': 'Upload',
    'common.change': 'Alterar',
    'common.remove': 'Remover',
    'common.select': 'Selecione...',
    'common.none': 'Nenhum',
    'common.active': 'Ativo',
    'common.inactive': 'Inativo',
    'common.generate': 'Gerar',
    'common.generating': 'Gerando...',
    'common.registered': 'Cadastrados',
    'common.activeNow': 'ativas no momento',
    'common.inSystem': 'Cadastrados no sistema',
    'common.activeCollaborators': 'Colaboradores ativos',
    'common.registeredEquipment': 'Equipamentos cadastrados',
    'common.locationsSpaces': 'Locais/espaços',
    'common.registeredPartners': 'Parceiros cadastrados',
    'common.allocatedResources': 'recurso(s) alocado(s)',
    'common.color': 'Cor',
    'common.type': 'Tipo',
    'common.category': 'Categoria',
    'common.phone': 'Telefone',
    'common.email': 'E-mail',
    'common.address': 'Endereço',
    'common.city': 'Cidade',
    'common.state': 'Estado',
    'common.zip': 'CEP',
    'common.country': 'País',
    'common.notes': 'Notas',
    'common.details': 'Detalhes',
    'common.info': 'Informações',
    'common.general': 'Geral',
    'common.all': 'Todos',
    'common.filter': 'Filtrar',
    'common.clear': 'Limpar',
    'common.apply': 'Aplicar',
    'common.close': 'Fechar',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    'common.previous': 'Anterior',
    'common.finish': 'Finalizar',
    'common.continue': 'Continuar',
    'common.confirm': 'Confirmar',
    'common.update': 'Atualizar',
    'common.create': 'Criar',
    'common.view': 'Visualizar',
    'common.download': 'Baixar',
    'common.export': 'Exportar',
    'common.import': 'Importar',
    'common.print': 'Imprimir',
    'common.copy': 'Copiar',
    'common.paste': 'Colar',
    'common.cut': 'Cortar',
    'common.undo': 'Desfazer',
    'common.redo': 'Refazer',
    'common.refresh': 'Atualizar',
    'common.reload': 'Recarregar',
    'common.reset': 'Redefinir',
    'common.start': 'Iniciar',
    'common.stop': 'Parar',
    'common.pause': 'Pausar',
    'common.resume': 'Retomar',
    'common.send': 'Enviar',
    'common.receive': 'Receber',
    'common.upload.formats': 'Formatos: JPG, PNG, GIF. Máx: 2MB',
    'common.clickToAdd': 'Clique para adicionar',
    'common.maxChars': 'Máx. 10 caracteres',
    'common.required': 'Campo obrigatório',
    
    // Theme
    'theme.dark': 'Tema Escuro',
    'theme.light': 'Tema Claro',
    'settings': 'Configurações',
    'language': 'Idioma',
    
    // Menu / Sidebar
    'menu.dashboard': 'Dashboard',
    'menu.production': 'Produção',
    'menu.content': 'Conteúdo',
    'menu.recordings': 'Gravação',
    'menu.maps': 'Mapas',
    'menu.resources': 'Recursos',
    'menu.people': 'Pessoas',
    'menu.humanResources': 'Recursos Humanos',
    'menu.technicalResources': 'Recursos Técnicos',
    'menu.physicalResources': 'Recursos Físicos',
    'menu.suppliers': 'Fornecedores',
    'menu.services': 'Serviços',
    'menu.costumes': 'Figurinos',
    'menu.admin': 'Administração',
    'menu.users': 'Usuários',
    'menu.accessProfiles': 'Perfil de Acesso',
    'menu.businessUnits': 'Unidade de Negócio',
    'menu.profitCenters': 'Centro de Lucro',
    'menu.parameters': 'Parametrizações',
    'menu.logout': 'Sair',
    'menu.recordingTypes': 'Tipos de Gravação',
    'menu.classification': 'Classificação',
    'menu.recordingStatus': 'Status de Gravação',
    'menu.positions': 'Cargos',
    'menu.departments': 'Departamentos',
    'menu.functions': 'Funções',
    'menu.supplierCategory': 'Categoria de Fornecedores',
    'menu.peopleClassification': 'Classificação Pessoas',
    'menu.costumeType': 'Tipo Figurino',
    'menu.material': 'Material',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.hello': 'Olá',
    'dashboard.welcome': 'Bem-vindo ao painel de controle do Kreato',
    'dashboard.overview': 'Visão Geral',
    'dashboard.recordings': 'Gravações',
    'dashboard.contents': 'Conteúdos',
    'dashboard.humanResources': 'Recursos Humanos',
    'dashboard.businessUnits': 'Unidades de Negócio',
    'dashboard.technicalResources': 'Recursos Técnicos',
    'dashboard.physicalResources': 'Recursos Físicos',
    'dashboard.suppliers': 'Fornecedores',
    'dashboard.upcomingRecordings': 'Próximas Gravações',
    'dashboard.recordingsThisWeek': 'Gravações com recursos alocados esta semana',
    'dashboard.noRecordingsThisWeek': 'Nenhuma gravação com recursos alocados esta semana',
    'dashboard.systemSummary': 'Resumo do Sistema',
    'dashboard.registryOverview': 'Visão geral dos cadastros',
    'dashboard.totalRecordings': 'Total de Gravações',
    'dashboard.totalContents': 'Total de Conteúdos',
    
    // Business Units
    'businessUnits.title': 'Unidades de Negócio',
    'businessUnits.description': 'Gerencie as unidades de negócio da organização',
    'businessUnits.new': 'Nova Unidade de Negócio',
    'businessUnits.edit': 'Editar Unidade de Negócio',
    'businessUnits.empty': 'Nenhuma unidade de negócio cadastrada',
    'businessUnits.emptyDescription': 'Comece adicionando unidades de negócio para organizar seu sistema.',
    'businessUnits.deleted': 'Unidade de Negócio removida com sucesso!',
    'businessUnits.saved': 'Unidade de Negócio salva com sucesso!',
    'businessUnits.updated': 'Unidade de Negócio atualizada com sucesso!',
    
    // Profit Centers
    'profitCenters.title': 'Centros de Lucro',
    'profitCenters.description': 'Gerencie os centros de lucro da organização',
    'profitCenters.new': 'Novo Centro de Lucro',
    'profitCenters.edit': 'Editar Centro de Lucro',
    
    // Users
    'users.title': 'Usuários',
    'users.description': 'Gerencie os usuários do sistema',
    'users.new': 'Novo Usuário',
    'users.edit': 'Editar Usuário',
    
    // Access Profiles
    'accessProfiles.title': 'Perfis de Acesso',
    'accessProfiles.description': 'Gerencie os perfis de acesso do sistema',
    'accessProfiles.new': 'Novo Perfil de Acesso',
    'accessProfiles.edit': 'Editar Perfil de Acesso',
    
    // Content
    'content.title': 'Conteúdo',
    'content.description': 'Gerencie os conteúdos de produção',
    'content.new': 'Novo Conteúdo',
    'content.edit': 'Editar Conteúdo',
    'content.episodes': 'Qtd. Episódios',
    'content.synopsis': 'Descrição / Sinopse',
    'content.productionYear': 'Ano de Produção',
    'content.contentType': 'Tipo de Conteúdo',
    'content.classification': 'Classificação',
    'content.empty': 'Nenhum conteúdo cadastrado',
    'content.emptyDescription': 'Comece adicionando conteúdos para organizar sua produção.',
    'content.noRecordings': 'Nenhuma gravação associada.',
    'content.clickGenerate': 'Clique em "Gerar" para criar as gravações automaticamente.',
    'content.contentRecordings': 'Gravações do Conteúdo',
    
    // Recordings
    'recordings.title': 'Gravações',
    'recordings.description': 'Gerencie as gravações de produção',
    'recordings.new': 'Nova Gravação',
    'recordings.edit': 'Editar Gravação',
    'recordings.expectedDate': 'Data Prevista',
    'recordings.generalData': 'Dados Gerais',
    'recordings.resources': 'Recursos',
    'recordings.cast': 'Elenco',
    'recordings.guests': 'Convidados',
    'recordings.costumes': 'Figurinos',
    'recordings.thirdParties': 'Terceiros',
    'recordings.costs': 'Custos',
    'recordings.empty': 'Nenhuma gravação cadastrada',
    'recordings.emptyDescription': 'Comece adicionando gravações para gerenciar sua produção.',
    'recordings.businessUnit': 'Unidade de Negócio',
    'recordings.profitCenter': 'Centro de Lucro',
    
    // Cast
    'cast.title': 'Elenco',
    'cast.add': 'Adicionar ao Elenco',
    'cast.person': 'Pessoa',
    'cast.character': 'Personagem',
    'cast.characterDescription': 'Descrição do Personagem',
    'cast.costumes': 'Figurinos do Personagem',
    'cast.actor': 'Ator/Atriz',
    'cast.empty': 'Nenhum membro do elenco adicionado',
    'cast.total': 'membro(s) do elenco',
    
    // Guests
    'guests.title': 'Convidados',
    'guests.add': 'Adicionar Convidado',
    'guests.roleInRecording': 'Função na Gravação',
    'guests.contact': 'Contato',
    'guests.empty': 'Nenhum convidado adicionado',
    'guests.total': 'convidado(s)',
    
    // Costumes / Figurinos
    'costumes.title': 'Figurinos',
    'costumes.description': 'Gerencie os figurinos disponíveis',
    'costumes.new': 'Novo Figurino',
    'costumes.edit': 'Editar Figurino',
    'costumes.code': 'Código do Figurino',
    'costumes.type': 'Tipo de Figurino',
    'costumes.size': 'Tamanho',
    'costumes.primaryColor': 'Cor Predominante',
    'costumes.secondaryColor': 'Cor Secundária',
    'costumes.material': 'Material',
    'costumes.images': 'Imagens',
    'costumes.mainImage': 'Imagem Principal',
    'costumes.empty': 'Nenhum figurino cadastrado',
    'costumes.emptyDescription': 'Comece adicionando figurinos para sua produção.',
    'costumes.addToCostume': 'Adicionar Figurino',
    'costumes.noCostumesAdded': 'Nenhum figurino adicionado a esta gravação',
    
    // People
    'people.title': 'Pessoas',
    'people.description': 'Gerencie o cadastro de pessoas',
    'people.new': 'Nova Pessoa',
    'people.edit': 'Editar Pessoa',
    'people.firstName': 'Nome',
    'people.lastName': 'Sobrenome',
    'people.workName': 'Nome Artístico',
    'people.phone': 'Telefone',
    'people.email': 'E-mail',
    'people.photo': 'Foto',
    'people.empty': 'Nenhuma pessoa cadastrada',
    'people.emptyDescription': 'Comece adicionando pessoas ao sistema.',
    
    // Human Resources
    'humanResources.title': 'Recursos Humanos',
    'humanResources.description': 'Gerencie os recursos humanos disponíveis',
    'humanResources.new': 'Novo Recurso Humano',
    'humanResources.edit': 'Editar Recurso Humano',
    'humanResources.empty': 'Nenhum recurso humano cadastrado',
    
    // Technical Resources
    'technicalResources.title': 'Recursos Técnicos',
    'technicalResources.description': 'Gerencie os recursos técnicos disponíveis',
    'technicalResources.new': 'Novo Recurso Técnico',
    'technicalResources.edit': 'Editar Recurso Técnico',
    'technicalResources.empty': 'Nenhum recurso técnico cadastrado',
    
    // Physical Resources
    'physicalResources.title': 'Recursos Físicos',
    'physicalResources.description': 'Gerencie os recursos físicos disponíveis',
    'physicalResources.new': 'Novo Recurso Físico',
    'physicalResources.edit': 'Editar Recurso Físico',
    'physicalResources.empty': 'Nenhum recurso físico cadastrado',
    
    // Suppliers
    'suppliers.title': 'Fornecedores',
    'suppliers.description': 'Gerencie os fornecedores',
    'suppliers.new': 'Novo Fornecedor',
    'suppliers.edit': 'Editar Fornecedor',
    'suppliers.empty': 'Nenhum fornecedor cadastrado',
    
    // Services
    'services.title': 'Serviços',
    'services.description': 'Gerencie os serviços disponíveis',
    'services.new': 'Novo Serviço',
    'services.edit': 'Editar Serviço',
    'services.empty': 'Nenhum serviço cadastrado',
    
    // Maps
    'maps.title': 'Mapas',
    'maps.description': 'Visualize os mapas de produção',
    
    // Parameters
    'parameters.positions': 'Cargos',
    'parameters.departments': 'Departamentos',
    'parameters.functions': 'Funções',
    'parameters.supplierCategories': 'Categorias de Fornecedores',
    'parameters.peopleClassification': 'Classificação de Pessoas',
    'parameters.costumeTypes': 'Tipos de Figurino',
    'parameters.materials': 'Materiais',
    'parameters.recordingTypes': 'Tipos de Gravação',
    'parameters.recordingStatus': 'Status de Gravação',
    'parameters.classification': 'Classificação',
    
    // Costs
    'costs.title': 'Custos',
    'costs.estimatedCost': 'Custo Estimado',
    'costs.actualCost': 'Custo Real',
    'costs.dailyRate': 'Diária',
    'costs.hourlyRate': 'Valor Hora',
    'costs.totalCost': 'Custo Total',
    
    // Third Parties
    'thirdParties.title': 'Terceiros',
    'thirdParties.add': 'Adicionar Terceiro',
    'thirdParties.empty': 'Nenhum terceiro adicionado',
    
    // Resources Tab
    'resourcesTab.allocate': 'Alocar Recurso',
    'resourcesTab.startDate': 'Data Início',
    'resourcesTab.endDate': 'Data Fim',
    'resourcesTab.noResourcesAllocated': 'Nenhum recurso alocado',
    
    // Currency
    'currency.symbol': 'R$',
    'currency.code': 'BRL',
  },
  en: {
    // Login
    'login.welcome': 'Welcome to Kreato',
    'login.subtitle': 'Production Management System',
    'login.user': 'User',
    'login.user.placeholder': 'Enter your username',
    'login.password': 'Password',
    'login.password.placeholder': 'Enter your password',
    'login.submit': 'Sign In',
    'login.loading': 'Signing in...',
    'login.error': 'Invalid user or password',
    'login.hint': 'Initial access: Admin / kreato',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.new': 'New',
    'common.search': 'Search...',
    'common.actions': 'Actions',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.loading': 'Loading...',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.deleted': 'Deleted',
    'common.confirm.delete': 'Do you really want to delete?',
    'common.noResults': 'No results found',
    'common.code': 'Code',
    'common.externalCode': 'External Code',
    'common.name': 'Name',
    'common.description': 'Description',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.user': 'User',
    'common.registrationDate': 'Registration Date',
    'common.registrationUser': 'Registered By',
    'common.total': 'Total',
    'common.quantity': 'Quantity',
    'common.value': 'Value',
    'common.observations': 'Notes',
    'common.image': 'Image',
    'common.logo': 'Logo',
    'common.upload': 'Upload',
    'common.change': 'Change',
    'common.remove': 'Remove',
    'common.select': 'Select...',
    'common.none': 'None',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.generate': 'Generate',
    'common.generating': 'Generating...',
    'common.registered': 'Registered',
    'common.activeNow': 'active now',
    'common.inSystem': 'Registered in system',
    'common.activeCollaborators': 'Active collaborators',
    'common.registeredEquipment': 'Registered equipment',
    'common.locationsSpaces': 'Locations/spaces',
    'common.registeredPartners': 'Registered partners',
    'common.allocatedResources': 'allocated resource(s)',
    'common.color': 'Color',
    'common.type': 'Type',
    'common.category': 'Category',
    'common.phone': 'Phone',
    'common.email': 'Email',
    'common.address': 'Address',
    'common.city': 'City',
    'common.state': 'State',
    'common.zip': 'ZIP Code',
    'common.country': 'Country',
    'common.notes': 'Notes',
    'common.details': 'Details',
    'common.info': 'Information',
    'common.general': 'General',
    'common.all': 'All',
    'common.filter': 'Filter',
    'common.clear': 'Clear',
    'common.apply': 'Apply',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.finish': 'Finish',
    'common.continue': 'Continue',
    'common.confirm': 'Confirm',
    'common.update': 'Update',
    'common.create': 'Create',
    'common.view': 'View',
    'common.download': 'Download',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.print': 'Print',
    'common.copy': 'Copy',
    'common.paste': 'Paste',
    'common.cut': 'Cut',
    'common.undo': 'Undo',
    'common.redo': 'Redo',
    'common.refresh': 'Refresh',
    'common.reload': 'Reload',
    'common.reset': 'Reset',
    'common.start': 'Start',
    'common.stop': 'Stop',
    'common.pause': 'Pause',
    'common.resume': 'Resume',
    'common.send': 'Send',
    'common.receive': 'Receive',
    'common.upload.formats': 'Formats: JPG, PNG, GIF. Max: 2MB',
    'common.clickToAdd': 'Click to add',
    'common.maxChars': 'Max 10 characters',
    'common.required': 'Required field',
    
    // Theme
    'theme.dark': 'Dark Theme',
    'theme.light': 'Light Theme',
    'settings': 'Settings',
    'language': 'Language',
    
    // Menu / Sidebar
    'menu.dashboard': 'Dashboard',
    'menu.production': 'Production',
    'menu.content': 'Content',
    'menu.recordings': 'Recordings',
    'menu.maps': 'Maps',
    'menu.resources': 'Resources',
    'menu.people': 'People',
    'menu.humanResources': 'Human Resources',
    'menu.technicalResources': 'Technical Resources',
    'menu.physicalResources': 'Physical Resources',
    'menu.suppliers': 'Suppliers',
    'menu.services': 'Services',
    'menu.costumes': 'Costumes',
    'menu.admin': 'Administration',
    'menu.users': 'Users',
    'menu.accessProfiles': 'Access Profile',
    'menu.businessUnits': 'Business Unit',
    'menu.profitCenters': 'Profit Center',
    'menu.parameters': 'Parameters',
    'menu.logout': 'Logout',
    'menu.recordingTypes': 'Recording Types',
    'menu.classification': 'Classification',
    'menu.recordingStatus': 'Recording Status',
    'menu.positions': 'Positions',
    'menu.departments': 'Departments',
    'menu.functions': 'Functions',
    'menu.supplierCategory': 'Supplier Categories',
    'menu.peopleClassification': 'People Classification',
    'menu.costumeType': 'Costume Type',
    'menu.material': 'Material',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.hello': 'Hello',
    'dashboard.welcome': 'Welcome to the Kreato control panel',
    'dashboard.overview': 'Overview',
    'dashboard.recordings': 'Recordings',
    'dashboard.contents': 'Contents',
    'dashboard.humanResources': 'Human Resources',
    'dashboard.businessUnits': 'Business Units',
    'dashboard.technicalResources': 'Technical Resources',
    'dashboard.physicalResources': 'Physical Resources',
    'dashboard.suppliers': 'Suppliers',
    'dashboard.upcomingRecordings': 'Upcoming Recordings',
    'dashboard.recordingsThisWeek': 'Recordings with resources allocated this week',
    'dashboard.noRecordingsThisWeek': 'No recordings with resources allocated this week',
    'dashboard.systemSummary': 'System Summary',
    'dashboard.registryOverview': 'Registry overview',
    'dashboard.totalRecordings': 'Total Recordings',
    'dashboard.totalContents': 'Total Contents',
    
    // Business Units
    'businessUnits.title': 'Business Units',
    'businessUnits.description': 'Manage organization business units',
    'businessUnits.new': 'New Business Unit',
    'businessUnits.edit': 'Edit Business Unit',
    'businessUnits.empty': 'No business units registered',
    'businessUnits.emptyDescription': 'Start adding business units to organize your system.',
    'businessUnits.deleted': 'Business Unit deleted successfully!',
    'businessUnits.saved': 'Business Unit saved successfully!',
    'businessUnits.updated': 'Business Unit updated successfully!',
    
    // Profit Centers
    'profitCenters.title': 'Profit Centers',
    'profitCenters.description': 'Manage organization profit centers',
    'profitCenters.new': 'New Profit Center',
    'profitCenters.edit': 'Edit Profit Center',
    
    // Users
    'users.title': 'Users',
    'users.description': 'Manage system users',
    'users.new': 'New User',
    'users.edit': 'Edit User',
    
    // Access Profiles
    'accessProfiles.title': 'Access Profiles',
    'accessProfiles.description': 'Manage system access profiles',
    'accessProfiles.new': 'New Access Profile',
    'accessProfiles.edit': 'Edit Access Profile',
    
    // Content
    'content.title': 'Content',
    'content.description': 'Manage production content',
    'content.new': 'New Content',
    'content.edit': 'Edit Content',
    'content.episodes': 'Episodes Qty',
    'content.synopsis': 'Description / Synopsis',
    'content.productionYear': 'Production Year',
    'content.contentType': 'Content Type',
    'content.classification': 'Classification',
    'content.empty': 'No content registered',
    'content.emptyDescription': 'Start adding content to organize your production.',
    'content.noRecordings': 'No recordings associated.',
    'content.clickGenerate': 'Click "Generate" to create recordings automatically.',
    'content.contentRecordings': 'Content Recordings',
    
    // Recordings
    'recordings.title': 'Recordings',
    'recordings.description': 'Manage production recordings',
    'recordings.new': 'New Recording',
    'recordings.edit': 'Edit Recording',
    'recordings.expectedDate': 'Expected Date',
    'recordings.generalData': 'General Data',
    'recordings.resources': 'Resources',
    'recordings.cast': 'Cast',
    'recordings.guests': 'Guests',
    'recordings.costumes': 'Costumes',
    'recordings.thirdParties': 'Third Parties',
    'recordings.costs': 'Costs',
    'recordings.empty': 'No recordings registered',
    'recordings.emptyDescription': 'Start adding recordings to manage your production.',
    'recordings.businessUnit': 'Business Unit',
    'recordings.profitCenter': 'Profit Center',
    
    // Cast
    'cast.title': 'Cast',
    'cast.add': 'Add to Cast',
    'cast.person': 'Person',
    'cast.character': 'Character',
    'cast.characterDescription': 'Character Description',
    'cast.costumes': 'Character Costumes',
    'cast.actor': 'Actor/Actress',
    'cast.empty': 'No cast members added',
    'cast.total': 'cast member(s)',
    
    // Guests
    'guests.title': 'Guests',
    'guests.add': 'Add Guest',
    'guests.roleInRecording': 'Role in Recording',
    'guests.contact': 'Contact',
    'guests.empty': 'No guests added',
    'guests.total': 'guest(s)',
    
    // Costumes
    'costumes.title': 'Costumes',
    'costumes.description': 'Manage available costumes',
    'costumes.new': 'New Costume',
    'costumes.edit': 'Edit Costume',
    'costumes.code': 'Costume Code',
    'costumes.type': 'Costume Type',
    'costumes.size': 'Size',
    'costumes.primaryColor': 'Primary Color',
    'costumes.secondaryColor': 'Secondary Color',
    'costumes.material': 'Material',
    'costumes.images': 'Images',
    'costumes.mainImage': 'Main Image',
    'costumes.empty': 'No costumes registered',
    'costumes.emptyDescription': 'Start adding costumes for your production.',
    'costumes.addToCostume': 'Add Costume',
    'costumes.noCostumesAdded': 'No costumes added to this recording',
    
    // People
    'people.title': 'People',
    'people.description': 'Manage people registry',
    'people.new': 'New Person',
    'people.edit': 'Edit Person',
    'people.firstName': 'First Name',
    'people.lastName': 'Last Name',
    'people.workName': 'Stage Name',
    'people.phone': 'Phone',
    'people.email': 'Email',
    'people.photo': 'Photo',
    'people.empty': 'No people registered',
    'people.emptyDescription': 'Start adding people to the system.',
    
    // Human Resources
    'humanResources.title': 'Human Resources',
    'humanResources.description': 'Manage available human resources',
    'humanResources.new': 'New Human Resource',
    'humanResources.edit': 'Edit Human Resource',
    'humanResources.empty': 'No human resources registered',
    
    // Technical Resources
    'technicalResources.title': 'Technical Resources',
    'technicalResources.description': 'Manage available technical resources',
    'technicalResources.new': 'New Technical Resource',
    'technicalResources.edit': 'Edit Technical Resource',
    'technicalResources.empty': 'No technical resources registered',
    
    // Physical Resources
    'physicalResources.title': 'Physical Resources',
    'physicalResources.description': 'Manage available physical resources',
    'physicalResources.new': 'New Physical Resource',
    'physicalResources.edit': 'Edit Physical Resource',
    'physicalResources.empty': 'No physical resources registered',
    
    // Suppliers
    'suppliers.title': 'Suppliers',
    'suppliers.description': 'Manage suppliers',
    'suppliers.new': 'New Supplier',
    'suppliers.edit': 'Edit Supplier',
    'suppliers.empty': 'No suppliers registered',
    
    // Services
    'services.title': 'Services',
    'services.description': 'Manage available services',
    'services.new': 'New Service',
    'services.edit': 'Edit Service',
    'services.empty': 'No services registered',
    
    // Maps
    'maps.title': 'Maps',
    'maps.description': 'View production maps',
    
    // Parameters
    'parameters.positions': 'Positions',
    'parameters.departments': 'Departments',
    'parameters.functions': 'Functions',
    'parameters.supplierCategories': 'Supplier Categories',
    'parameters.peopleClassification': 'People Classification',
    'parameters.costumeTypes': 'Costume Types',
    'parameters.materials': 'Materials',
    'parameters.recordingTypes': 'Recording Types',
    'parameters.recordingStatus': 'Recording Status',
    'parameters.classification': 'Classification',
    
    // Costs
    'costs.title': 'Costs',
    'costs.estimatedCost': 'Estimated Cost',
    'costs.actualCost': 'Actual Cost',
    'costs.dailyRate': 'Daily Rate',
    'costs.hourlyRate': 'Hourly Rate',
    'costs.totalCost': 'Total Cost',
    
    // Third Parties
    'thirdParties.title': 'Third Parties',
    'thirdParties.add': 'Add Third Party',
    'thirdParties.empty': 'No third parties added',
    
    // Resources Tab
    'resourcesTab.allocate': 'Allocate Resource',
    'resourcesTab.startDate': 'Start Date',
    'resourcesTab.endDate': 'End Date',
    'resourcesTab.noResourcesAllocated': 'No resources allocated',
    
    // Currency
    'currency.symbol': '$',
    'currency.code': 'USD',
  },
  es: {
    // Login
    'login.welcome': 'Bienvenido a Kreato',
    'login.subtitle': 'Sistema de Gestión de Producción',
    'login.user': 'Usuario',
    'login.user.placeholder': 'Ingrese su usuario',
    'login.password': 'Contraseña',
    'login.password.placeholder': 'Ingrese su contraseña',
    'login.submit': 'Iniciar Sesión',
    'login.loading': 'Iniciando...',
    'login.error': 'Usuario o contraseña inválidos',
    'login.hint': 'Acceso inicial: Admin / kreato',
    
    // Common
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.add': 'Agregar',
    'common.new': 'Nuevo',
    'common.search': 'Buscar...',
    'common.actions': 'Acciones',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.loading': 'Cargando...',
    'common.success': 'Éxito',
    'common.error': 'Error',
    'common.deleted': 'Eliminado',
    'common.confirm.delete': '¿Realmente desea eliminar?',
    'common.noResults': 'No se encontraron resultados',
    'common.code': 'Código',
    'common.externalCode': 'Código Externo',
    'common.name': 'Nombre',
    'common.description': 'Descripción',
    'common.status': 'Estado',
    'common.date': 'Fecha',
    'common.user': 'Usuario',
    'common.registrationDate': 'Fecha de Registro',
    'common.registrationUser': 'Registrado Por',
    'common.total': 'Total',
    'common.quantity': 'Cantidad',
    'common.value': 'Valor',
    'common.observations': 'Observaciones',
    'common.image': 'Imagen',
    'common.logo': 'Logotipo',
    'common.upload': 'Subir',
    'common.change': 'Cambiar',
    'common.remove': 'Eliminar',
    'common.select': 'Seleccione...',
    'common.none': 'Ninguno',
    'common.active': 'Activo',
    'common.inactive': 'Inactivo',
    'common.generate': 'Generar',
    'common.generating': 'Generando...',
    'common.registered': 'Registrados',
    'common.activeNow': 'activas ahora',
    'common.inSystem': 'Registrados en el sistema',
    'common.activeCollaborators': 'Colaboradores activos',
    'common.registeredEquipment': 'Equipos registrados',
    'common.locationsSpaces': 'Ubicaciones/espacios',
    'common.registeredPartners': 'Socios registrados',
    'common.allocatedResources': 'recurso(s) asignado(s)',
    'common.color': 'Color',
    'common.type': 'Tipo',
    'common.category': 'Categoría',
    'common.phone': 'Teléfono',
    'common.email': 'Correo',
    'common.address': 'Dirección',
    'common.city': 'Ciudad',
    'common.state': 'Estado',
    'common.zip': 'Código Postal',
    'common.country': 'País',
    'common.notes': 'Notas',
    'common.details': 'Detalles',
    'common.info': 'Información',
    'common.general': 'General',
    'common.all': 'Todos',
    'common.filter': 'Filtrar',
    'common.clear': 'Limpiar',
    'common.apply': 'Aplicar',
    'common.close': 'Cerrar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.finish': 'Finalizar',
    'common.continue': 'Continuar',
    'common.confirm': 'Confirmar',
    'common.update': 'Actualizar',
    'common.create': 'Crear',
    'common.view': 'Ver',
    'common.download': 'Descargar',
    'common.export': 'Exportar',
    'common.import': 'Importar',
    'common.print': 'Imprimir',
    'common.copy': 'Copiar',
    'common.paste': 'Pegar',
    'common.cut': 'Cortar',
    'common.undo': 'Deshacer',
    'common.redo': 'Rehacer',
    'common.refresh': 'Actualizar',
    'common.reload': 'Recargar',
    'common.reset': 'Restablecer',
    'common.start': 'Iniciar',
    'common.stop': 'Detener',
    'common.pause': 'Pausar',
    'common.resume': 'Reanudar',
    'common.send': 'Enviar',
    'common.receive': 'Recibir',
    'common.upload.formats': 'Formatos: JPG, PNG, GIF. Máx: 2MB',
    'common.clickToAdd': 'Haga clic para agregar',
    'common.maxChars': 'Máx 10 caracteres',
    'common.required': 'Campo obligatorio',
    
    // Theme
    'theme.dark': 'Tema Oscuro',
    'theme.light': 'Tema Claro',
    'settings': 'Configuración',
    'language': 'Idioma',
    
    // Menu / Sidebar
    'menu.dashboard': 'Panel',
    'menu.production': 'Producción',
    'menu.content': 'Contenido',
    'menu.recordings': 'Grabaciones',
    'menu.maps': 'Mapas',
    'menu.resources': 'Recursos',
    'menu.people': 'Personas',
    'menu.humanResources': 'Recursos Humanos',
    'menu.technicalResources': 'Recursos Técnicos',
    'menu.physicalResources': 'Recursos Físicos',
    'menu.suppliers': 'Proveedores',
    'menu.services': 'Servicios',
    'menu.costumes': 'Vestuarios',
    'menu.admin': 'Administración',
    'menu.users': 'Usuarios',
    'menu.accessProfiles': 'Perfil de Acceso',
    'menu.businessUnits': 'Unidad de Negocio',
    'menu.profitCenters': 'Centro de Beneficio',
    'menu.parameters': 'Parámetros',
    'menu.logout': 'Salir',
    'menu.recordingTypes': 'Tipos de Grabación',
    'menu.classification': 'Clasificación',
    'menu.recordingStatus': 'Estado de Grabación',
    'menu.positions': 'Cargos',
    'menu.departments': 'Departamentos',
    'menu.functions': 'Funciones',
    'menu.supplierCategory': 'Categorías de Proveedores',
    'menu.peopleClassification': 'Clasificación de Personas',
    'menu.costumeType': 'Tipo de Vestuario',
    'menu.material': 'Material',
    
    // Dashboard
    'dashboard.title': 'Panel',
    'dashboard.hello': 'Hola',
    'dashboard.welcome': 'Bienvenido al panel de control de Kreato',
    'dashboard.overview': 'Resumen',
    'dashboard.recordings': 'Grabaciones',
    'dashboard.contents': 'Contenidos',
    'dashboard.humanResources': 'Recursos Humanos',
    'dashboard.businessUnits': 'Unidades de Negocio',
    'dashboard.technicalResources': 'Recursos Técnicos',
    'dashboard.physicalResources': 'Recursos Físicos',
    'dashboard.suppliers': 'Proveedores',
    'dashboard.upcomingRecordings': 'Próximas Grabaciones',
    'dashboard.recordingsThisWeek': 'Grabaciones con recursos asignados esta semana',
    'dashboard.noRecordingsThisWeek': 'No hay grabaciones con recursos asignados esta semana',
    'dashboard.systemSummary': 'Resumen del Sistema',
    'dashboard.registryOverview': 'Visión general de registros',
    'dashboard.totalRecordings': 'Total de Grabaciones',
    'dashboard.totalContents': 'Total de Contenidos',
    
    // Business Units
    'businessUnits.title': 'Unidades de Negocio',
    'businessUnits.description': 'Gestione las unidades de negocio de la organización',
    'businessUnits.new': 'Nueva Unidad de Negocio',
    'businessUnits.edit': 'Editar Unidad de Negocio',
    'businessUnits.empty': 'No hay unidades de negocio registradas',
    'businessUnits.emptyDescription': 'Comience agregando unidades de negocio para organizar su sistema.',
    'businessUnits.deleted': '¡Unidad de Negocio eliminada con éxito!',
    'businessUnits.saved': '¡Unidad de Negocio guardada con éxito!',
    'businessUnits.updated': '¡Unidad de Negocio actualizada con éxito!',
    
    // Profit Centers
    'profitCenters.title': 'Centros de Beneficio',
    'profitCenters.description': 'Gestione los centros de beneficio de la organización',
    'profitCenters.new': 'Nuevo Centro de Beneficio',
    'profitCenters.edit': 'Editar Centro de Beneficio',
    
    // Users
    'users.title': 'Usuarios',
    'users.description': 'Gestione los usuarios del sistema',
    'users.new': 'Nuevo Usuario',
    'users.edit': 'Editar Usuario',
    
    // Access Profiles
    'accessProfiles.title': 'Perfiles de Acceso',
    'accessProfiles.description': 'Gestione los perfiles de acceso del sistema',
    'accessProfiles.new': 'Nuevo Perfil de Acceso',
    'accessProfiles.edit': 'Editar Perfil de Acceso',
    
    // Content
    'content.title': 'Contenido',
    'content.description': 'Gestione los contenidos de producción',
    'content.new': 'Nuevo Contenido',
    'content.edit': 'Editar Contenido',
    'content.episodes': 'Cant. Episodios',
    'content.synopsis': 'Descripción / Sinopsis',
    'content.productionYear': 'Año de Producción',
    'content.contentType': 'Tipo de Contenido',
    'content.classification': 'Clasificación',
    'content.empty': 'No hay contenido registrado',
    'content.emptyDescription': 'Comience agregando contenido para organizar su producción.',
    'content.noRecordings': 'No hay grabaciones asociadas.',
    'content.clickGenerate': 'Haga clic en "Generar" para crear las grabaciones automáticamente.',
    'content.contentRecordings': 'Grabaciones del Contenido',
    
    // Recordings
    'recordings.title': 'Grabaciones',
    'recordings.description': 'Gestione las grabaciones de producción',
    'recordings.new': 'Nueva Grabación',
    'recordings.edit': 'Editar Grabación',
    'recordings.expectedDate': 'Fecha Prevista',
    'recordings.generalData': 'Datos Generales',
    'recordings.resources': 'Recursos',
    'recordings.cast': 'Elenco',
    'recordings.guests': 'Invitados',
    'recordings.costumes': 'Vestuarios',
    'recordings.thirdParties': 'Terceros',
    'recordings.costs': 'Costos',
    'recordings.empty': 'No hay grabaciones registradas',
    'recordings.emptyDescription': 'Comience agregando grabaciones para gestionar su producción.',
    'recordings.businessUnit': 'Unidad de Negocio',
    'recordings.profitCenter': 'Centro de Beneficio',
    
    // Cast
    'cast.title': 'Elenco',
    'cast.add': 'Agregar al Elenco',
    'cast.person': 'Persona',
    'cast.character': 'Personaje',
    'cast.characterDescription': 'Descripción del Personaje',
    'cast.costumes': 'Vestuarios del Personaje',
    'cast.actor': 'Actor/Actriz',
    'cast.empty': 'Ningún miembro del elenco agregado',
    'cast.total': 'miembro(s) del elenco',
    
    // Guests
    'guests.title': 'Invitados',
    'guests.add': 'Agregar Invitado',
    'guests.roleInRecording': 'Función en la Grabación',
    'guests.contact': 'Contacto',
    'guests.empty': 'Ningún invitado agregado',
    'guests.total': 'invitado(s)',
    
    // Costumes
    'costumes.title': 'Vestuarios',
    'costumes.description': 'Gestione los vestuarios disponibles',
    'costumes.new': 'Nuevo Vestuario',
    'costumes.edit': 'Editar Vestuario',
    'costumes.code': 'Código del Vestuario',
    'costumes.type': 'Tipo de Vestuario',
    'costumes.size': 'Tamaño',
    'costumes.primaryColor': 'Color Predominante',
    'costumes.secondaryColor': 'Color Secundario',
    'costumes.material': 'Material',
    'costumes.images': 'Imágenes',
    'costumes.mainImage': 'Imagen Principal',
    'costumes.empty': 'No hay vestuarios registrados',
    'costumes.emptyDescription': 'Comience agregando vestuarios para su producción.',
    'costumes.addToCostume': 'Agregar Vestuario',
    'costumes.noCostumesAdded': 'No hay vestuarios agregados a esta grabación',
    
    // People
    'people.title': 'Personas',
    'people.description': 'Gestione el registro de personas',
    'people.new': 'Nueva Persona',
    'people.edit': 'Editar Persona',
    'people.firstName': 'Nombre',
    'people.lastName': 'Apellido',
    'people.workName': 'Nombre Artístico',
    'people.phone': 'Teléfono',
    'people.email': 'Correo',
    'people.photo': 'Foto',
    'people.empty': 'No hay personas registradas',
    'people.emptyDescription': 'Comience agregando personas al sistema.',
    
    // Human Resources
    'humanResources.title': 'Recursos Humanos',
    'humanResources.description': 'Gestione los recursos humanos disponibles',
    'humanResources.new': 'Nuevo Recurso Humano',
    'humanResources.edit': 'Editar Recurso Humano',
    'humanResources.empty': 'No hay recursos humanos registrados',
    
    // Technical Resources
    'technicalResources.title': 'Recursos Técnicos',
    'technicalResources.description': 'Gestione los recursos técnicos disponibles',
    'technicalResources.new': 'Nuevo Recurso Técnico',
    'technicalResources.edit': 'Editar Recurso Técnico',
    'technicalResources.empty': 'No hay recursos técnicos registrados',
    
    // Physical Resources
    'physicalResources.title': 'Recursos Físicos',
    'physicalResources.description': 'Gestione los recursos físicos disponibles',
    'physicalResources.new': 'Nuevo Recurso Físico',
    'physicalResources.edit': 'Editar Recurso Físico',
    'physicalResources.empty': 'No hay recursos físicos registrados',
    
    // Suppliers
    'suppliers.title': 'Proveedores',
    'suppliers.description': 'Gestione los proveedores',
    'suppliers.new': 'Nuevo Proveedor',
    'suppliers.edit': 'Editar Proveedor',
    'suppliers.empty': 'No hay proveedores registrados',
    
    // Services
    'services.title': 'Servicios',
    'services.description': 'Gestione los servicios disponibles',
    'services.new': 'Nuevo Servicio',
    'services.edit': 'Editar Servicio',
    'services.empty': 'No hay servicios registrados',
    
    // Maps
    'maps.title': 'Mapas',
    'maps.description': 'Visualice los mapas de producción',
    
    // Parameters
    'parameters.positions': 'Cargos',
    'parameters.departments': 'Departamentos',
    'parameters.functions': 'Funciones',
    'parameters.supplierCategories': 'Categorías de Proveedores',
    'parameters.peopleClassification': 'Clasificación de Personas',
    'parameters.costumeTypes': 'Tipos de Vestuario',
    'parameters.materials': 'Materiales',
    'parameters.recordingTypes': 'Tipos de Grabación',
    'parameters.recordingStatus': 'Estado de Grabación',
    'parameters.classification': 'Clasificación',
    
    // Costs
    'costs.title': 'Costos',
    'costs.estimatedCost': 'Costo Estimado',
    'costs.actualCost': 'Costo Real',
    'costs.dailyRate': 'Tarifa Diaria',
    'costs.hourlyRate': 'Tarifa por Hora',
    'costs.totalCost': 'Costo Total',
    
    // Third Parties
    'thirdParties.title': 'Terceros',
    'thirdParties.add': 'Agregar Tercero',
    'thirdParties.empty': 'No hay terceros agregados',
    
    // Resources Tab
    'resourcesTab.allocate': 'Asignar Recurso',
    'resourcesTab.startDate': 'Fecha Inicio',
    'resourcesTab.endDate': 'Fecha Fin',
    'resourcesTab.noResourcesAllocated': 'No hay recursos asignados',
    
    // Currency
    'currency.symbol': '€',
    'currency.code': 'EUR',
  },
};

// Currency locale mapping
const currencyLocales: Record<Language, { locale: string; currency: string }> = {
  pt: { locale: 'pt-BR', currency: 'BRL' },
  en: { locale: 'en-US', currency: 'USD' },
  es: { locale: 'es-ES', currency: 'EUR' },
};

// Language labels
export const languageLabels: Record<Language, { name: string; flag: string }> = {
  pt: { name: 'Português', flag: '🇧🇷' },
  en: { name: 'English', flag: '🇺🇸' },
  es: { name: 'Español', flag: '🇪🇸' },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('kreato_language');
    return (stored as Language) || 'pt';
  });

  useEffect(() => {
    localStorage.setItem('kreato_language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const formatCurrency = (value: number): string => {
    const { locale, currency } = currencyLocales[language];
    return new Intl.NumberFormat(locale, {
      style: 'currency',
      currency,
    }).format(value);
  };

  const formatDate = (date: Date | string): string => {
    const { locale } = currencyLocales[language];
    const dateObj = typeof date === 'string' ? new Date(date) : date;
    return new Intl.DateTimeFormat(locale).format(dateObj);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, formatCurrency, formatDate }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
