import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'pt' | 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  formatCurrency: (value: number) => string;
  formatDate: (date: Date | string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations
const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Login
    'login.welcome': 'Bem-vindo ao Kreato',
    'login.subtitle': 'Sistema de Gestão de Produção',
    'login.user': 'Usuário',
    'login.user.placeholder': 'Digite seu usuário',
    'login.password': 'Senha',
    'login.password.placeholder': 'Digite sua senha',
    'login.submit': 'Entrar no Sistema',
    'login.loading': 'Entrando...',
    'login.error': 'Usuário ou senha inválidos',
    'login.hint': 'Acesso inicial: Admin / kreato',
    
    // Common
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.add': 'Adicionar',
    'common.new': 'Novo',
    'common.search': 'Pesquisar...',
    'common.actions': 'Ações',
    'common.yes': 'Sim',
    'common.no': 'Não',
    'common.loading': 'Carregando...',
    'common.success': 'Sucesso',
    'common.error': 'Erro',
    'common.deleted': 'Excluído',
    'common.confirm.delete': 'Deseja realmente excluir?',
    'common.noResults': 'Nenhum resultado encontrado',
    'common.code': 'Código',
    'common.externalCode': 'Código Externo',
    'common.name': 'Nome',
    'common.description': 'Descrição',
    'common.status': 'Status',
    'common.date': 'Data',
    'common.user': 'Usuário',
    'common.registrationDate': 'Data de Cadastro',
    'common.registrationUser': 'Usuário de Cadastro',
    'common.total': 'Total',
    'common.quantity': 'Quantidade',
    'common.value': 'Valor',
    'common.observations': 'Observações',
    'common.image': 'Imagem',
    'common.logo': 'Logotipo',
    'common.upload': 'Upload',
    'common.change': 'Alterar',
    'common.remove': 'Remover',
    'common.select': 'Selecione...',
    'common.none': 'Nenhum',
    'common.active': 'Ativo',
    'common.inactive': 'Inativo',
    'common.generate': 'Gerar',
    'common.generating': 'Gerando...',
    'common.registered': 'Cadastrados',
    'common.activeNow': 'ativas no momento',
    'common.inSystem': 'Cadastrados no sistema',
    'common.activeCollaborators': 'Colaboradores ativos',
    'common.registeredEquipment': 'Equipamentos cadastrados',
    'common.locationsSpaces': 'Locais/espaços',
    'common.registeredPartners': 'Parceiros cadastrados',
    'common.allocatedResources': 'recurso(s) alocado(s)',
    'common.color': 'Cor',
    'common.type': 'Tipo',
    'common.category': 'Categoria',
    'common.phone': 'Telefone',
    'common.email': 'E-mail',
    'common.address': 'Endereço',
    'common.city': 'Cidade',
    'common.state': 'Estado',
    'common.zip': 'CEP',
    'common.country': 'País',
    'common.notes': 'Notas',
    'common.details': 'Detalhes',
    'common.info': 'Informações',
    'common.general': 'Geral',
    'common.all': 'Todos',
    'common.filter': 'Filtrar',
    'common.clear': 'Limpar',
    'common.apply': 'Aplicar',
    'common.close': 'Fechar',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    'common.previous': 'Anterior',
    'common.finish': 'Finalizar',
    'common.continue': 'Continuar',
    'common.confirm': 'Confirmar',
    'common.update': 'Atualizar',
    'common.create': 'Criar',
    'common.view': 'Visualizar',
    'common.download': 'Baixar',
    'common.export': 'Exportar',
    'common.import': 'Importar',
    'common.print': 'Imprimir',
    'common.copy': 'Copiar',
    'common.paste': 'Colar',
    'common.cut': 'Cortar',
    'common.undo': 'Desfazer',
    'common.redo': 'Refazer',
    'common.refresh': 'Atualizar',
    'common.reload': 'Recarregar',
    'common.reset': 'Redefinir',
    'common.start': 'Iniciar',
    'common.stop': 'Parar',
    'common.pause': 'Pausar',
    'common.resume': 'Retomar',
    'common.send': 'Enviar',
    'common.receive': 'Receber',
    'common.upload.formats': 'Formatos: JPG, PNG, GIF. Máx: 2MB',
    'common.clickToAdd': 'Clique para adicionar',
    'common.maxChars': 'Máx. 10 caracteres',
    'common.required': 'Campo obrigatório',
    'common.startTime': 'Hora Início',
    'common.endTime': 'Hora Fim',
    
    // Theme
    'theme.dark': 'Tema Escuro',
    'theme.light': 'Tema Claro',
    'settings': 'Configurações',
    'language': 'Idioma',
    
    // Menu / Sidebar
    'menu.dashboard': 'Dashboard',
    'menu.production': 'Produção',
    'menu.content': 'Conteúdo',
    'menu.recordings': 'Gravação',
    'menu.maps': 'Mapas',
    'menu.resources': 'Recursos',
    'menu.people': 'Pessoas',
    'menu.humanResources': 'Recursos Humanos',
    'menu.technicalResources': 'Recursos Técnicos',
    'menu.physicalResources': 'Recursos Físicos',
    'menu.suppliers': 'Fornecedores',
    'menu.services': 'Serviços',
    'menu.costumes': 'Figurinos',
    'menu.admin': 'Administração',
    'menu.users': 'Usuários',
    'menu.accessProfiles': 'Perfil de Acesso',
    'menu.businessUnits': 'Unidade de Negócio',
    'menu.profitCenters': 'Centro de Lucro',
    'menu.forms': 'Formulários',
    'menu.parameters': 'Parametrizações',
    'menu.logout': 'Sair',
    'menu.recordingTypes': 'Tipos de Gravação',
    'menu.classification': 'Classificação',
    'menu.recordingStatus': 'Status de Gravação',
    'menu.tasks': 'Tarefas',
    'menu.taskStatus': 'Status de Tarefa',
    'menu.priceTables': 'Tabelas de Preços',
    'menu.positions': 'Cargos',
    'menu.departments': 'Departamentos',
    'menu.functions': 'Funções',
    'menu.supplierCategory': 'Categoria de Fornecedores',
    'menu.peopleClassification': 'Classificação Pessoas',
    'menu.costumeType': 'Tipo Figurino',
    'menu.material': 'Material',
    'menu.teams': 'Equipes',
    
    // Tasks
    'tasks.title': 'Tarefas',
    'tasks.description': 'Gerencie as tarefas da produção',
    'tasks.new': 'Nova Tarefa',
    'tasks.edit': 'Editar Tarefa',
    'tasks.total': 'Total de Tarefas',
    'tasks.pending': 'Pendentes',
    'tasks.inProgress': 'Em Progresso',
    'tasks.completed': 'Concluídas',
    'tasks.empty': 'Nenhuma tarefa cadastrada',
    'tasks.addFirst': 'Adicionar primeira tarefa',
    'tasks.created': 'Tarefa criada com sucesso!',
    'tasks.updated': 'Tarefa atualizada com sucesso!',
    'tasks.taskTitle': 'Título da Tarefa',
    'tasks.taskTitlePlaceholder': 'Digite o título da tarefa',
    'tasks.taskDescription': 'Descrição',
    'tasks.taskDescriptionPlaceholder': 'Descreva a tarefa',
    'tasks.recording': 'Gravação',
    'tasks.status': 'Status',
    'tasks.assignee': 'Responsável',
    'tasks.priority': 'Prioridade',
    'tasks.priorityLow': 'Baixa',
    'tasks.priorityMedium': 'Média',
    'tasks.priorityHigh': 'Alta',
    'tasks.startDate': 'Data Início',
    'tasks.dueDate': 'Data Limite',
    'tasks.formDescription': 'Preencha os dados da tarefa',
    'tasks.deleteConfirmation': 'Esta ação não pode ser desfeita.',
    'tasks.filterByStatus': 'Filtrar por status',
    'tasks.filterByRecording': 'Filtrar por gravação',
    
    // Parameters
    'parameters.taskStatus': 'Status de Tarefa',
    'parameters.taskStatusDescription': 'Configure os status disponíveis para as tarefas',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.hello': 'Olá',
    'dashboard.welcome': 'Bem-vindo ao painel de controle do Kreato',
    'dashboard.overview': 'Visão Geral',
    'dashboard.recordings': 'Gravações',
    'dashboard.contents': 'Conteúdos',
    'dashboard.humanResources': 'Recursos Humanos',
    'dashboard.businessUnits': 'Unidades de Negócio',
    'dashboard.technicalResources': 'Recursos Técnicos',
    'dashboard.physicalResources': 'Recursos Físicos',
    'dashboard.suppliers': 'Fornecedores',
    'dashboard.upcomingRecordings': 'Próximas Gravações',
    'dashboard.recordingsThisWeek': 'Gravações com recursos alocados esta semana',
    'dashboard.noRecordingsThisWeek': 'Nenhuma gravação com recursos alocados esta semana',
    'dashboard.systemSummary': 'Resumo do Sistema',
    'dashboard.registryOverview': 'Visão geral dos cadastros',
    'dashboard.totalRecordings': 'Total de Gravações',
    'dashboard.totalContents': 'Total de Conteúdos',
    
    // Business Units
    'businessUnits.title': 'Unidades de Negócio',
    'businessUnits.description': 'Gerencie as unidades de negócio da organização',
    'businessUnits.new': 'Nova Unidade de Negócio',
    'businessUnits.edit': 'Editar Unidade de Negócio',
    'businessUnits.empty': 'Nenhuma unidade de negócio cadastrada',
    'businessUnits.emptyDescription': 'Comece adicionando unidades de negócio para organizar seu sistema.',
    'businessUnits.deleted': 'Unidade de Negócio removida com sucesso!',
    'businessUnits.saved': 'Unidade de Negócio salva com sucesso!',
    'businessUnits.updated': 'Unidade de Negócio atualizada com sucesso!',
    
    // Profit Centers
    'profitCenters.title': 'Centros de Lucro',
    'profitCenters.description': 'Gerencie os centros de lucro da organização',
    'profitCenters.new': 'Novo Centro de Lucro',
    'profitCenters.edit': 'Editar Centro de Lucro',
    
    // Users
    'users.title': 'Usuários',
    'users.description': 'Gerencie os usuários do sistema',
    'users.new': 'Novo Usuário',
    'users.edit': 'Editar Usuário',
    
    // Access Profiles
    'accessProfiles.title': 'Perfis de Acesso',
    'accessProfiles.description': 'Gerencie os perfis de acesso do sistema',
    'accessProfiles.new': 'Novo Perfil de Acesso',
    'accessProfiles.edit': 'Editar Perfil de Acesso',
    
    // Content
    'content.title': 'Conteúdo',
    'content.description': 'Gerencie os conteúdos de produção',
    'content.new': 'Novo Conteúdo',
    'content.edit': 'Editar Conteúdo',
    'content.episodes': 'Qtd. Episódios',
    'content.synopsis': 'Descrição / Sinopse',
    'content.productionYear': 'Ano de Produção',
    'content.contentType': 'Tipo de Conteúdo',
    'content.classification': 'Classificação',
    'content.empty': 'Nenhum conteúdo cadastrado',
    'content.emptyDescription': 'Comece adicionando conteúdos para organizar sua produção.',
    'content.noRecordings': 'Nenhuma gravação associada.',
    'content.clickGenerate': 'Clique em "Gerar" para criar as gravações automaticamente.',
    'content.contentRecordings': 'Gravações do Conteúdo',
    
    // Recordings
    'recordings.title': 'Gravações',
    'recordings.description': 'Gerencie as gravações de produção',
    'recordings.new': 'Nova Gravação',
    'recordings.edit': 'Editar Gravação',
    'recordings.expectedDate': 'Data Prevista',
    'recordings.generalData': 'Dados Gerais',
    'recordings.resources': 'Recursos',
    'recordings.cast': 'Elenco',
    'recordings.guests': 'Convidados',
    'recordings.costumes': 'Figurinos',
    'recordings.thirdParties': 'Terceiros',
    'recordings.costs': 'Custos',
    'recordings.empty': 'Nenhuma gravação cadastrada',
    'recordings.emptyDescription': 'Comece adicionando gravações para gerenciar sua produção.',
    'recordings.businessUnit': 'Unidade de Negócio',
    'recordings.profitCenter': 'Centro de Lucro',
    
    // Cast
    'cast.title': 'Elenco',
    'cast.add': 'Adicionar ao Elenco',
    'cast.person': 'Pessoa',
    'cast.character': 'Personagem',
    'cast.characterDescription': 'Descrição do Personagem',
    'cast.costumes': 'Figurinos do Personagem',
    'cast.actor': 'Ator/Atriz',
    'cast.empty': 'Nenhum membro do elenco adicionado',
    'cast.total': 'membro(s) do elenco',
    
    // Guests
    'guests.title': 'Convidados',
    'guests.add': 'Adicionar Convidado',
    'guests.roleInRecording': 'Função na Gravação',
    'guests.contact': 'Contato',
    'guests.empty': 'Nenhum convidado adicionado',
    'guests.total': 'convidado(s)',
    
    // Costumes / Figurinos
    'costumes.title': 'Figurinos',
    'costumes.description': 'Gerencie os figurinos disponíveis',
    'costumes.new': 'Novo Figurino',
    'costumes.edit': 'Editar Figurino',
    'costumes.code': 'Código do Figurino',
    'costumes.type': 'Tipo de Figurino',
    'costumes.size': 'Tamanho',
    'costumes.primaryColor': 'Cor Predominante',
    'costumes.secondaryColor': 'Cor Secundária',
    'costumes.material': 'Material',
    'costumes.images': 'Imagens',
    'costumes.mainImage': 'Imagem Principal',
    'costumes.empty': 'Nenhum figurino cadastrado',
    'costumes.emptyDescription': 'Comece adicionando figurinos para sua produção.',
    'costumes.addToCostume': 'Adicionar Figurino',
    'costumes.noCostumesAdded': 'Nenhum figurino adicionado a esta gravação',
    
    // People
    'people.title': 'Pessoas',
    'people.description': 'Gerencie o cadastro de pessoas',
    'people.new': 'Nova Pessoa',
    'people.edit': 'Editar Pessoa',
    'people.firstName': 'Nome',
    'people.lastName': 'Sobrenome',
    'people.workName': 'Nome Artístico',
    'people.phone': 'Telefone',
    'people.email': 'E-mail',
    'people.photo': 'Foto',
    'people.empty': 'Nenhuma pessoa cadastrada',
    'people.emptyDescription': 'Comece adicionando pessoas ao sistema.',
    
    // Human Resources
    'humanResources.title': 'Recursos Humanos',
    'humanResources.description': 'Gerencie os recursos humanos disponíveis',
    'humanResources.new': 'Novo Recurso Humano',
    'humanResources.edit': 'Editar Recurso Humano',
    'humanResources.empty': 'Nenhum recurso humano cadastrado',
    
    // Technical Resources
    'technicalResources.title': 'Recursos Técnicos',
    'technicalResources.description': 'Gerencie os recursos técnicos disponíveis',
    'technicalResources.new': 'Novo Recurso Técnico',
    'technicalResources.edit': 'Editar Recurso Técnico',
    'technicalResources.empty': 'Nenhum recurso técnico cadastrado',
    
    // Physical Resources
    'physicalResources.title': 'Recursos Físicos',
    'physicalResources.description': 'Gerencie os recursos físicos disponíveis',
    'physicalResources.new': 'Novo Recurso Físico',
    'physicalResources.edit': 'Editar Recurso Físico',
    'physicalResources.empty': 'Nenhum recurso físico cadastrado',
    
    // Suppliers
    'suppliers.title': 'Fornecedores',
    'suppliers.description': 'Gerencie os fornecedores',
    'suppliers.new': 'Novo Fornecedor',
    'suppliers.edit': 'Editar Fornecedor',
    'suppliers.empty': 'Nenhum fornecedor cadastrado',
    
    // Services
    'services.title': 'Serviços',
    'services.description': 'Gerencie os serviços disponíveis',
    'services.new': 'Novo Serviço',
    'services.edit': 'Editar Serviço',
    'services.empty': 'Nenhum serviço cadastrado',
    
    // Maps
    'maps.title': 'Mapas',
    'maps.description': 'Visualize os mapas de produção',
    'maps.physicalResources': 'Recursos Físicos',
    'maps.humanResources': 'Recursos Humanos',
    'maps.costAppropriation': 'Apropriação de Custos',
    
    // Parameters
    'parameters.positions': 'Cargos',
    'parameters.departments': 'Departamentos',
    'parameters.functions': 'Funções',
    'parameters.supplierCategories': 'Categorias de Fornecedores',
    'parameters.peopleClassification': 'Classificação de Pessoas',
    'parameters.costumeTypes': 'Tipos de Figurino',
    'parameters.materials': 'Materiais',
    'parameters.recordingTypes': 'Tipos de Gravação',
    'parameters.recordingStatus': 'Status de Gravação',
    'parameters.classification': 'Classificação',
    
    // Costs
    'costs.title': 'Custos',
    'costs.estimatedCost': 'Custo Estimado',
    'costs.actualCost': 'Custo Real',
    'costs.dailyRate': 'Diária',
    'costs.hourlyRate': 'Valor Hora',
    'costs.totalCost': 'Custo Total',
    
    // Third Parties
    'thirdParties.title': 'Terceiros',
    'thirdParties.add': 'Adicionar Terceiro',
    'thirdParties.empty': 'Nenhum terceiro adicionado',
    
    // Resources Tab
    'resourcesTab.allocate': 'Alocar Recurso',
    'resourcesTab.startDate': 'Data Início',
    'resourcesTab.endDate': 'Data Fim',
    'resourcesTab.noResourcesAllocated': 'Nenhum recurso alocado',
    
    // Script/Roteiro
    'script.title': 'Roteiro de Gravação',
    'script.description': 'Organize a ordem das cenas a serem gravadas',
    'script.addScene': 'Adicionar Cena',
    'script.noScenes': 'Nenhuma cena cadastrada',
    'script.addFirstScene': 'Adicionar primeira cena',
    'script.sceneAdded': 'Cena adicionada com sucesso!',
    'script.sceneRemoved': 'Cena removida com sucesso!',
    'script.chapter': 'Capítulo',
    'script.sceneNumber': 'Número da Cena',
    'script.environment': 'Ambiente',
    'script.environmentType': 'Tipo de Ambiente',
    'script.period': 'Período',
    'script.rhythm': 'Ritmo',
    'script.recordingLocation': 'Local da Gravação',
    'script.approximateTime': 'Tempo Aproximado',
    'script.charactersInScene': 'Personagens em Cena (do Elenco)',
    'script.noCast': 'Nenhum elenco cadastrado. Adicione membros ao elenco no tabulador "Elenco".',
    'script.extras': 'Figurantes (Pessoas classificadas como Figurante)',
    'script.noExtras': 'Nenhuma pessoa classificada como "Figurante". Cadastre pessoas no módulo Recursos > Pessoas.',
    'script.sceneDescription': 'Descrição da Cena',
    'script.formatHint': 'Use marcações de texto: *texto* para itálico, **texto** para negrito',
    'script.external': 'Externo',
    'script.internal': 'Interno',
    'script.day': 'Dia',
    'script.night': 'Noite',
    'script.morning': 'Manhã',
    'script.afternoon': 'Tarde',
    'script.dawn': 'Madrugada',
    'script.dramatic': 'Dramático',
    'script.fastScene': 'Cena Rápida',
    'script.contemplative': 'Contemplativa',
    'script.scene': 'Cena',
    'script.selectCharacters': 'Selecionar Personagens',
    'script.searchCharacter': 'Buscar personagem...',
    'script.selectExtras': 'Selecionar Figurantes',
    'script.searchExtra': 'Buscar figurante...',
    'script.exportPDF': 'Exportar PDF',
    'script.exportSuccess': 'Roteiro exportado com sucesso!',
    'script.noScenesToExport': 'Nenhuma cena para exportar',
    'common.of': 'de',
    
    // Costs Tab
    'costsTab.noCosts': 'Nenhum custo estimado',
    'costsTab.noCostsDescription': 'Aloque recursos com horários definidos na aba "Recursos" para visualizar a estimativa de custos.',
    'costsTab.totalHours': 'Total de Horas',
    'costsTab.estimatedHours': 'Horas estimadas de trabalho',
    'costsTab.totalCost': 'Custo Total',
    'costsTab.estimatedCost': 'Custo estimado da gravação',
    'costsTab.costItems': 'Itens de Custo',
    'costsTab.allocatedWithCost': 'Recursos alocados com custo',
    'costsTab.humanResources': 'Recursos Humanos',
    'costsTab.physicalResources': 'Recursos Físicos',
    'costsTab.resource': 'Recurso',
    'costsTab.hours': 'Horas',
    'costsTab.hourlyRate': 'Custo/Hora',
    'costsTab.daysOccupation': 'dia(s) de ocupação',
    'costsTab.daysIn': 'dia(s) em',
    'costsTab.subtotal': 'Subtotal',
    'costsTab.totalEstimatedCost': 'Custo Total Estimado',
    'costsTab.workHours': 'horas de trabalho',
    
    // Fields / Columns / Modals
    'field.department': 'Departamento',
    'field.function': 'Função',
    'field.costPerHour': 'Custo/Hora',
    'field.stock': 'Estoque',
    'field.photo': 'Foto',
    'field.lastName': 'Sobrenome',
    'field.gender': 'Sexo',
    'field.male': 'Masculino',
    'field.female': 'Feminino',
    'field.other': 'Outro',
    'field.birthDate': 'Data de Nascimento',
    'field.hireDate': 'Data de Contratação',
    'field.personalData': 'Dados Pessoais',
    'field.absences': 'Ausências',
    'field.schedules': 'Escalas',
    'field.attachments': 'Anexos',
    'field.collaborator': 'Colaborador',
    'field.newCollaborator': 'Novo Colaborador',
    'field.editCollaborator': 'Editar Colaborador',
    'field.fillCollaboratorData': 'Preencha os dados do colaborador.',
    'field.operatorFunction': 'Função do Operador',
    'field.operatorFunctionHint': 'Define qual função pode operar este recurso',
    'field.selectFunction': 'Selecione a função...',
    'field.availability': 'Disponibilidade',
    'field.availabilityRanges': 'Faixas de Disponibilidade',
    'field.addRange': 'Adicionar Faixa',
    'field.range': 'Faixa',
    'field.noRanges': 'Nenhuma faixa de disponibilidade cadastrada.',
    'field.clickAddRange': 'Clique em "Adicionar Faixa" para definir períodos de disponibilidade.',
    'field.startDate': 'Data Início',
    'field.endDate': 'Data Fim',
    'field.startTime': 'Hora Início',
    'field.endTime': 'Hora Fim',
    'field.weekDays': 'Dias da Semana',
    'field.classification': 'Classificação',
    'field.cityState': 'Cidade/Estado',
    'field.fiscalId': 'Identificação Fiscal',
    'field.generalData': 'Dados Gerais',
    'field.workName': 'Nome de Trabalho',
    'field.workNamePlaceholder': 'Nome artístico ou de trabalho',
    'field.document': 'CPF/Documento',
    'field.addAttachment': 'Adicionar Anexo',
    'field.noAttachments': 'Nenhum anexo adicionado',
    'field.attachmentsMaxSize': 'Anexos (máx. 2MB por arquivo)',
    'field.addAbsencePeriod': 'Adicionar Período de Ausência',
    'field.noAbsences': 'Nenhuma ausência cadastrada',
    'field.absencesHint': 'Adicione períodos de férias, folgas ou licenças',
    'field.absenceOverlapWarning': 'O sistema não permite cadastrar ausências com datas sobrepostas. Verifique se o período informado não conflita com ausências já existentes.',
    'field.addSchedule': 'Adicionar Escala',
    'field.noSchedules': 'Nenhuma escala cadastrada',
    'field.schedulesHint': 'Adicione escalas de trabalho com horários e dias da semana',
    'field.scheduleOverlapWarning': 'O sistema não permite cadastrar escalas com períodos sobrepostos.',
    'field.scaleMap': 'Mapa de Escalas',
    'field.availabilityMap': 'Mapa de Disponibilidade',
    'field.days': 'Dias',
    'field.reason': 'Motivo',
    'field.vacation': 'Férias',
    'field.dayOff': 'Folga',
    'field.maternityLeave': 'Licença Maternidade',
    'field.paternityLeave': 'Licença Paternidade',
    'field.externalCourse': 'Curso Externo',
    'field.businessTrip': 'Viagem de Trabalho',
    'field.selectDepartmentFirst': 'Selecione um departamento primeiro',
    'field.noFunctionsRegistered': 'Nenhuma função cadastrada',
    'field.overlapWarning': 'Esta faixa se sobrepõe a outra faixa existente.',
    'field.fillFieldsFor': 'Preencha os campos para',
    'field.thePhysicalResource': 'o recurso físico.',
    'field.services': 'Serviços',
    'field.files': 'Arquivos',
    'field.fillSupplierData': 'Preencha os dados do fornecedor.',
    'field.selectClassification': 'Selecione a classificação',
    'field.manageCollaborators': 'Gerencie os colaboradores da organização',
    'field.noCollaboratorRegistered': 'Nenhum colaborador cadastrado',
    'field.addCollaborator': 'Adicionar Colaborador',
    'field.manageCollaboratorsTeam': 'Adicione colaboradores para gerenciar sua equipe.',
    'field.managePhysicalResources': 'Gerencie os recursos físicos (espaços, estúdios, etc.)',
    'field.noPhysicalResourceRegistered': 'Nenhum recurso físico cadastrado',
    'field.addPhysicalResource': 'Adicionar Recurso',
    'field.physicalResourcesHint': 'Adicione recursos físicos como estúdios e salas.',
    'field.manageTechnicalResources': 'Gerencie os recursos técnicos disponíveis',
    'field.noTechnicalResourceRegistered': 'Nenhum recurso técnico cadastrado',
    'field.addTechnicalResource': 'Adicionar Recurso',
    'field.technicalResourcesHint': 'Adicione recursos técnicos para utilizar nas gravações.',
    'field.managePeople': 'Gerencie as pessoas cadastradas no sistema',
    'field.noPersonRegistered': 'Nenhuma pessoa cadastrada',
    'field.addPerson': 'Adicionar Pessoa',
    'field.peopleHint': 'Adicione pessoas para gerenciar seu cadastro.',
    'field.manageSuppliers': 'Gerencie os fornecedores de serviços',
    'field.noSupplierRegistered': 'Nenhum fornecedor cadastrado',
    'field.addSupplier': 'Adicionar Fornecedor',
    'field.suppliersHint': 'Adicione fornecedores para gerenciar parcerias.',
    'field.newResource': 'Novo Recurso',
    'field.newPerson': 'Nova Pessoa',
    'field.newSupplier': 'Novo Fornecedor',
    'field.editSupplier': 'Editar Fornecedor',
    'field.suppliers': 'Fornecedores',
    'field.budget': 'Orçamento',
    'field.selectUnitFirst': 'Selecione uma Unidade primeiro',
    'field.selectUnitToEnable': 'Selecione uma Unidade de Negócio para habilitar',
    'field.budgetPlaceholder': 'Valor do orçamento',
    'field.recordings': 'Gravações',
    'field.cast': 'Elenco',
    'field.costs': 'Custos',
    'field.noRecordings': 'Nenhuma gravação associada.',
    'field.clickGenerate': 'Clique em "Gerar" para criar as gravações automaticamente.',
    'field.noStatus': 'Sem status',
    'field.saveBeforeGenerating': 'Salve o conteúdo antes de gerar gravações.',
    'field.defineEpisodesFirst': 'Defina a quantidade de episódios antes de gerar.',
    'field.allRecordingsGenerated': 'Todas as gravações já foram geradas para este conteúdo.',
    'field.recordingsGenerated': 'gravações geradas com sucesso!',
    'field.descriptionRequired': 'Descrição é obrigatória.',
    'field.fillContentData': 'Preencha os campos para cadastrar o conteúdo.',
    'field.editContentData': 'Preencha os campos para editar o conteúdo.',
    'field.confirmDeleteContent': 'Deseja realmente excluir este conteúdo? Todas as gravações associadas também serão removidas.',
    'field.contentDeleteBlocked': 'Este conteúdo possui gravações com recursos, técnicos, físicos ou terceiros associados.',
    'field.contentDeleted': 'Conteúdo e gravações associadas removidos!',
    'field.contentUpdated': 'Conteúdo atualizado!',
    'field.contentCreated': 'Conteúdo cadastrado!',
    'field.contentLoadError': 'Erro ao carregar conteúdos',
    'field.contentSaveError': 'Erro ao salvar conteúdo',
    'field.contentDeleteError': 'Erro ao excluir conteúdo',
    'field.confirmDeleteSupplier': 'Deseja realmente excluir este fornecedor?',
    'field.supplierUpdated': 'Fornecedor atualizado!',
    'field.supplierCreated': 'Fornecedor cadastrado!',
    'field.supplierDeleted': 'Fornecedor removido!',
    'field.supplierLoadError': 'Erro ao carregar fornecedores',
    'field.supplierSaveError': 'Erro ao salvar fornecedor',
    'field.supplierDeleteError': 'Erro ao excluir fornecedor',
    'field.sun': 'Dom',
    'field.mon': 'Seg',
    'field.tue': 'Ter',
    'field.wed': 'Qua',
    'field.thu': 'Qui',
    'field.fri': 'Sex',
    'field.sat': 'Sáb',
    
    // Teams
    'teams.title': 'Equipes',
    'teams.description': 'Gerencie as equipes de recursos humanos',
    'teams.new': 'Nova Equipe',
    'teams.edit': 'Editar Equipe',
    'teams.empty': 'Nenhuma equipe cadastrada. Adicione uma equipe.',
    'teams.created': 'Equipe criada com sucesso!',
    'teams.updated': 'Equipe atualizada com sucesso!',
    'teams.deleted': 'Equipe removida com sucesso!',
    'teams.loadError': 'Erro ao carregar equipes',
    'teams.saveError': 'Erro ao salvar equipe',
    'teams.deleteError': 'Erro ao excluir equipe',
    'teams.members': 'Membros',
    'teams.membersList': 'Membros da Equipe',
    'teams.addMember': 'Adicionar Membro',
    'teams.selectMember': 'Selecione um recurso humano.',
    'teams.selectMemberPlaceholder': 'Selecione um recurso humano...',
    'teams.saveFirst': 'Salve a equipe antes de adicionar membros.',
    'teams.memberAdded': 'Membro adicionado com sucesso!',
    'teams.memberRemoved': 'Membro removido com sucesso!',
    'teams.memberAddError': 'Erro ao adicionar membro.',
    'teams.memberRemoveError': 'Erro ao remover membro.',
    'teams.memberNotFound': 'Recurso não encontrado',
    'teams.noMembers': 'Nenhum membro na equipe.',
    'teams.addMemberHint': 'Clique em "Adicionar Membro" para incluir.',
    'teams.newDescription': 'Cadastrar nova equipe.',
    'teams.editDescription': 'Editar equipe.',
    'teams.function': 'Função',

    // Currency
    'currency.symbol': 'R$',
    'currency.code': 'BRL',
  },
  en: {
    // Login
    'login.welcome': 'Welcome to Kreato',
    'login.subtitle': 'Production Management System',
    'login.user': 'User',
    'login.user.placeholder': 'Enter your username',
    'login.password': 'Password',
    'login.password.placeholder': 'Enter your password',
    'login.submit': 'Sign In',
    'login.loading': 'Signing in...',
    'login.error': 'Invalid user or password',
    'login.hint': 'Initial access: Admin / kreato',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.new': 'New',
    'common.search': 'Search...',
    'common.actions': 'Actions',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.loading': 'Loading...',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.deleted': 'Deleted',
    'common.confirm.delete': 'Do you really want to delete?',
    'common.noResults': 'No results found',
    'common.code': 'Code',
    'common.externalCode': 'External Code',
    'common.name': 'Name',
    'common.description': 'Description',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.user': 'User',
    'common.registrationDate': 'Registration Date',
    'common.registrationUser': 'Registered By',
    'common.total': 'Total',
    'common.quantity': 'Quantity',
    'common.value': 'Value',
    'common.observations': 'Notes',
    'common.image': 'Image',
    'common.logo': 'Logo',
    'common.upload': 'Upload',
    'common.change': 'Change',
    'common.remove': 'Remove',
    'common.select': 'Select...',
    'common.none': 'None',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.generate': 'Generate',
    'common.generating': 'Generating...',
    'common.registered': 'Registered',
    'common.activeNow': 'active now',
    'common.inSystem': 'Registered in system',
    'common.activeCollaborators': 'Active collaborators',
    'common.registeredEquipment': 'Registered equipment',
    'common.locationsSpaces': 'Locations/spaces',
    'common.registeredPartners': 'Registered partners',
    'common.allocatedResources': 'allocated resource(s)',
    'common.color': 'Color',
    'common.type': 'Type',
    'common.category': 'Category',
    'common.phone': 'Phone',
    'common.email': 'Email',
    'common.address': 'Address',
    'common.city': 'City',
    'common.state': 'State',
    'common.zip': 'ZIP Code',
    'common.country': 'Country',
    'common.notes': 'Notes',
    'common.details': 'Details',
    'common.info': 'Information',
    'common.general': 'General',
    'common.all': 'All',
    'common.filter': 'Filter',
    'common.clear': 'Clear',
    'common.apply': 'Apply',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.finish': 'Finish',
    'common.continue': 'Continue',
    'common.confirm': 'Confirm',
    'common.update': 'Update',
    'common.create': 'Create',
    'common.view': 'View',
    'common.download': 'Download',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.print': 'Print',
    'common.copy': 'Copy',
    'common.paste': 'Paste',
    'common.cut': 'Cut',
    'common.undo': 'Undo',
    'common.redo': 'Redo',
    'common.refresh': 'Refresh',
    'common.reload': 'Reload',
    'common.reset': 'Reset',
    'common.start': 'Start',
    'common.stop': 'Stop',
    'common.pause': 'Pause',
    'common.resume': 'Resume',
    'common.send': 'Send',
    'common.receive': 'Receive',
    'common.upload.formats': 'Formats: JPG, PNG, GIF. Max: 2MB',
    'common.clickToAdd': 'Click to add',
    'common.maxChars': 'Max 10 characters',
    'common.required': 'Required field',
    'common.startTime': 'Start Time',
    'common.endTime': 'End Time',
    
    // Theme
    'theme.dark': 'Dark Theme',
    'theme.light': 'Light Theme',
    'settings': 'Settings',
    'language': 'Language',
    
    // Menu / Sidebar
    'menu.dashboard': 'Dashboard',
    'menu.production': 'Production',
    'menu.content': 'Content',
    'menu.recordings': 'Recordings',
    'menu.maps': 'Maps',
    'menu.resources': 'Resources',
    'menu.people': 'People',
    'menu.humanResources': 'Human Resources',
    'menu.technicalResources': 'Technical Resources',
    'menu.physicalResources': 'Physical Resources',
    'menu.suppliers': 'Suppliers',
    'menu.services': 'Services',
    'menu.costumes': 'Costumes',
    'menu.admin': 'Administration',
    'menu.users': 'Users',
    'menu.accessProfiles': 'Access Profile',
    'menu.businessUnits': 'Business Unit',
    'menu.profitCenters': 'Profit Center',
    'menu.forms': 'Forms',
    'menu.parameters': 'Parameters',
    'menu.logout': 'Logout',
    'menu.recordingTypes': 'Recording Types',
    'menu.classification': 'Classification',
    'menu.recordingStatus': 'Recording Status',
    'menu.tasks': 'Tasks',
    'menu.taskStatus': 'Task Status',
    'menu.priceTables': 'Price Tables',
    'menu.positions': 'Positions',
    'menu.departments': 'Departments',
    'menu.functions': 'Functions',
    'menu.supplierCategory': 'Supplier Categories',
    'menu.peopleClassification': 'People Classification',
    'menu.costumeType': 'Costume Type',
    'menu.material': 'Material',
    'menu.teams': 'Teams',
    
    // Tasks
    'tasks.title': 'Tasks',
    'tasks.description': 'Manage production tasks',
    'tasks.new': 'New Task',
    'tasks.edit': 'Edit Task',
    'tasks.total': 'Total Tasks',
    'tasks.pending': 'Pending',
    'tasks.inProgress': 'In Progress',
    'tasks.completed': 'Completed',
    'tasks.empty': 'No tasks registered',
    'tasks.addFirst': 'Add first task',
    'tasks.created': 'Task created successfully!',
    'tasks.updated': 'Task updated successfully!',
    'tasks.taskTitle': 'Task Title',
    'tasks.taskTitlePlaceholder': 'Enter task title',
    'tasks.taskDescription': 'Description',
    'tasks.taskDescriptionPlaceholder': 'Describe the task',
    'tasks.recording': 'Recording',
    'tasks.status': 'Status',
    'tasks.assignee': 'Assignee',
    'tasks.priority': 'Priority',
    'tasks.priorityLow': 'Low',
    'tasks.priorityMedium': 'Medium',
    'tasks.priorityHigh': 'High',
    'tasks.startDate': 'Start Date',
    'tasks.dueDate': 'Due Date',
    'tasks.formDescription': 'Fill in task details',
    'tasks.deleteConfirmation': 'This action cannot be undone.',
    'tasks.filterByStatus': 'Filter by status',
    'tasks.filterByRecording': 'Filter by recording',
    
    // Parameters
    'parameters.taskStatus': 'Task Status',
    'parameters.taskStatusDescription': 'Configure available task statuses',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.hello': 'Hello',
    'dashboard.welcome': 'Welcome to the Kreato control panel',
    'dashboard.overview': 'Overview',
    'dashboard.recordings': 'Recordings',
    'dashboard.contents': 'Contents',
    'dashboard.humanResources': 'Human Resources',
    'dashboard.businessUnits': 'Business Units',
    'dashboard.technicalResources': 'Technical Resources',
    'dashboard.physicalResources': 'Physical Resources',
    'dashboard.suppliers': 'Suppliers',
    'dashboard.upcomingRecordings': 'Upcoming Recordings',
    'dashboard.recordingsThisWeek': 'Recordings with resources allocated this week',
    'dashboard.noRecordingsThisWeek': 'No recordings with resources allocated this week',
    'dashboard.systemSummary': 'System Summary',
    'dashboard.registryOverview': 'Registry overview',
    'dashboard.totalRecordings': 'Total Recordings',
    'dashboard.totalContents': 'Total Contents',
    
    // Business Units
    'businessUnits.title': 'Business Units',
    'businessUnits.description': 'Manage organization business units',
    'businessUnits.new': 'New Business Unit',
    'businessUnits.edit': 'Edit Business Unit',
    'businessUnits.empty': 'No business units registered',
    'businessUnits.emptyDescription': 'Start adding business units to organize your system.',
    'businessUnits.deleted': 'Business Unit deleted successfully!',
    'businessUnits.saved': 'Business Unit saved successfully!',
    'businessUnits.updated': 'Business Unit updated successfully!',
    
    // Profit Centers
    'profitCenters.title': 'Profit Centers',
    'profitCenters.description': 'Manage organization profit centers',
    'profitCenters.new': 'New Profit Center',
    'profitCenters.edit': 'Edit Profit Center',
    
    // Users
    'users.title': 'Users',
    'users.description': 'Manage system users',
    'users.new': 'New User',
    'users.edit': 'Edit User',
    
    // Access Profiles
    'accessProfiles.title': 'Access Profiles',
    'accessProfiles.description': 'Manage system access profiles',
    'accessProfiles.new': 'New Access Profile',
    'accessProfiles.edit': 'Edit Access Profile',
    
    // Content
    'content.title': 'Content',
    'content.description': 'Manage production content',
    'content.new': 'New Content',
    'content.edit': 'Edit Content',
    'content.episodes': 'Episodes Qty',
    'content.synopsis': 'Description / Synopsis',
    'content.productionYear': 'Production Year',
    'content.contentType': 'Content Type',
    'content.classification': 'Classification',
    'content.empty': 'No content registered',
    'content.emptyDescription': 'Start adding content to organize your production.',
    'content.noRecordings': 'No recordings associated.',
    'content.clickGenerate': 'Click "Generate" to create recordings automatically.',
    'content.contentRecordings': 'Content Recordings',
    
    // Recordings
    'recordings.title': 'Recordings',
    'recordings.description': 'Manage production recordings',
    'recordings.new': 'New Recording',
    'recordings.edit': 'Edit Recording',
    'recordings.expectedDate': 'Expected Date',
    'recordings.generalData': 'General Data',
    'recordings.resources': 'Resources',
    'recordings.cast': 'Cast',
    'recordings.guests': 'Guests',
    'recordings.costumes': 'Costumes',
    'recordings.thirdParties': 'Third Parties',
    'recordings.costs': 'Costs',
    'recordings.empty': 'No recordings registered',
    'recordings.emptyDescription': 'Start adding recordings to manage your production.',
    'recordings.businessUnit': 'Business Unit',
    'recordings.profitCenter': 'Profit Center',
    
    // Cast
    'cast.title': 'Cast',
    'cast.add': 'Add to Cast',
    'cast.person': 'Person',
    'cast.character': 'Character',
    'cast.characterDescription': 'Character Description',
    'cast.costumes': 'Character Costumes',
    'cast.actor': 'Actor/Actress',
    'cast.empty': 'No cast members added',
    'cast.total': 'cast member(s)',
    
    // Guests
    'guests.title': 'Guests',
    'guests.add': 'Add Guest',
    'guests.roleInRecording': 'Role in Recording',
    'guests.contact': 'Contact',
    'guests.empty': 'No guests added',
    'guests.total': 'guest(s)',
    
    // Costumes
    'costumes.title': 'Costumes',
    'costumes.description': 'Manage available costumes',
    'costumes.new': 'New Costume',
    'costumes.edit': 'Edit Costume',
    'costumes.code': 'Costume Code',
    'costumes.type': 'Costume Type',
    'costumes.size': 'Size',
    'costumes.primaryColor': 'Primary Color',
    'costumes.secondaryColor': 'Secondary Color',
    'costumes.material': 'Material',
    'costumes.images': 'Images',
    'costumes.mainImage': 'Main Image',
    'costumes.empty': 'No costumes registered',
    'costumes.emptyDescription': 'Start adding costumes for your production.',
    'costumes.addToCostume': 'Add Costume',
    'costumes.noCostumesAdded': 'No costumes added to this recording',
    
    // People
    'people.title': 'People',
    'people.description': 'Manage people registry',
    'people.new': 'New Person',
    'people.edit': 'Edit Person',
    'people.firstName': 'First Name',
    'people.lastName': 'Last Name',
    'people.workName': 'Stage Name',
    'people.phone': 'Phone',
    'people.email': 'Email',
    'people.photo': 'Photo',
    'people.empty': 'No people registered',
    'people.emptyDescription': 'Start adding people to the system.',
    
    // Human Resources
    'humanResources.title': 'Human Resources',
    'humanResources.description': 'Manage available human resources',
    'humanResources.new': 'New Human Resource',
    'humanResources.edit': 'Edit Human Resource',
    'humanResources.empty': 'No human resources registered',
    
    // Technical Resources
    'technicalResources.title': 'Technical Resources',
    'technicalResources.description': 'Manage available technical resources',
    'technicalResources.new': 'New Technical Resource',
    'technicalResources.edit': 'Edit Technical Resource',
    'technicalResources.empty': 'No technical resources registered',
    
    // Physical Resources
    'physicalResources.title': 'Physical Resources',
    'physicalResources.description': 'Manage available physical resources',
    'physicalResources.new': 'New Physical Resource',
    'physicalResources.edit': 'Edit Physical Resource',
    'physicalResources.empty': 'No physical resources registered',
    
    // Suppliers
    'suppliers.title': 'Suppliers',
    'suppliers.description': 'Manage suppliers',
    'suppliers.new': 'New Supplier',
    'suppliers.edit': 'Edit Supplier',
    'suppliers.empty': 'No suppliers registered',
    
    // Services
    'services.title': 'Services',
    'services.description': 'Manage available services',
    'services.new': 'New Service',
    'services.edit': 'Edit Service',
    'services.empty': 'No services registered',
    
    // Maps
    'maps.title': 'Maps',
    'maps.description': 'View production maps',
    'maps.physicalResources': 'Physical Resources',
    'maps.humanResources': 'Human Resources',
    'maps.costAppropriation': 'Cost Appropriation',
    
    // Parameters
    'parameters.positions': 'Positions',
    'parameters.departments': 'Departments',
    'parameters.functions': 'Functions',
    'parameters.supplierCategories': 'Supplier Categories',
    'parameters.peopleClassification': 'People Classification',
    'parameters.costumeTypes': 'Costume Types',
    'parameters.materials': 'Materials',
    'parameters.recordingTypes': 'Recording Types',
    'parameters.recordingStatus': 'Recording Status',
    'parameters.classification': 'Classification',
    
    // Costs
    'costs.title': 'Costs',
    'costs.estimatedCost': 'Estimated Cost',
    'costs.actualCost': 'Actual Cost',
    'costs.dailyRate': 'Daily Rate',
    'costs.hourlyRate': 'Hourly Rate',
    'costs.totalCost': 'Total Cost',
    
    // Third Parties
    'thirdParties.title': 'Third Parties',
    'thirdParties.add': 'Add Third Party',
    'thirdParties.empty': 'No third parties added',
    
    // Resources Tab
    'resourcesTab.allocate': 'Allocate Resource',
    'resourcesTab.startDate': 'Start Date',
    'resourcesTab.endDate': 'End Date',
    'resourcesTab.noResourcesAllocated': 'No resources allocated',
    
    // Script/Roteiro
    'script.title': 'Recording Script',
    'script.description': 'Organize the order of scenes to be recorded',
    'script.addScene': 'Add Scene',
    'script.noScenes': 'No scenes registered',
    'script.addFirstScene': 'Add first scene',
    'script.sceneAdded': 'Scene added successfully!',
    'script.sceneRemoved': 'Scene removed successfully!',
    'script.chapter': 'Chapter',
    'script.sceneNumber': 'Scene Number',
    'script.environment': 'Environment',
    'script.environmentType': 'Environment Type',
    'script.period': 'Period',
    'script.rhythm': 'Rhythm',
    'script.recordingLocation': 'Recording Location',
    'script.approximateTime': 'Approximate Time',
    'script.charactersInScene': 'Characters in Scene (from Cast)',
    'script.noCast': 'No cast registered. Add cast members in the "Cast" tab.',
    'script.extras': 'Extras (People classified as Extra)',
    'script.noExtras': 'No person classified as "Extra". Register people in Resources > People.',
    'script.sceneDescription': 'Scene Description',
    'script.formatHint': 'Use text markers: *text* for italic, **text** for bold',
    'script.external': 'External',
    'script.internal': 'Internal',
    'script.day': 'Day',
    'script.night': 'Night',
    'script.morning': 'Morning',
    'script.afternoon': 'Afternoon',
    'script.dawn': 'Dawn',
    'script.dramatic': 'Dramatic',
    'script.fastScene': 'Fast Scene',
    'script.contemplative': 'Contemplative',
    'script.scene': 'Scene',
    'script.selectCharacters': 'Select Characters',
    'script.searchCharacter': 'Search character...',
    'script.selectExtras': 'Select Extras',
    'script.searchExtra': 'Search extra...',
    'script.exportPDF': 'Export PDF',
    'script.exportSuccess': 'Script exported successfully!',
    'script.noScenesToExport': 'No scenes to export',
    'common.of': 'of',
    
    // Costs Tab
    'costsTab.noCosts': 'No estimated costs',
    'costsTab.noCostsDescription': 'Allocate resources with defined schedules in the "Resources" tab to view cost estimates.',
    'costsTab.totalHours': 'Total Hours',
    'costsTab.estimatedHours': 'Estimated work hours',
    'costsTab.totalCost': 'Total Cost',
    'costsTab.estimatedCost': 'Estimated recording cost',
    'costsTab.costItems': 'Cost Items',
    'costsTab.allocatedWithCost': 'Resources allocated with cost',
    'costsTab.humanResources': 'Human Resources',
    'costsTab.physicalResources': 'Physical Resources',
    'costsTab.resource': 'Resource',
    'costsTab.hours': 'Hours',
    'costsTab.hourlyRate': 'Cost/Hour',
    'costsTab.daysOccupation': 'day(s) of occupation',
    'costsTab.daysIn': 'day(s) in',
    'costsTab.subtotal': 'Subtotal',
    'costsTab.totalEstimatedCost': 'Total Estimated Cost',
    'costsTab.workHours': 'work hours',
    
    // Fields / Columns / Modals
    'field.department': 'Department',
    'field.function': 'Function',
    'field.costPerHour': 'Cost/Hour',
    'field.stock': 'Stock',
    'field.photo': 'Photo',
    'field.lastName': 'Last Name',
    'field.gender': 'Gender',
    'field.male': 'Male',
    'field.female': 'Female',
    'field.other': 'Other',
    'field.birthDate': 'Date of Birth',
    'field.hireDate': 'Hire Date',
    'field.personalData': 'Personal Data',
    'field.absences': 'Absences',
    'field.schedules': 'Schedules',
    'field.attachments': 'Attachments',
    'field.collaborator': 'Collaborator',
    'field.newCollaborator': 'New Collaborator',
    'field.editCollaborator': 'Edit Collaborator',
    'field.fillCollaboratorData': 'Fill in collaborator data.',
    'field.operatorFunction': 'Operator Function',
    'field.operatorFunctionHint': 'Defines which function can operate this resource',
    'field.selectFunction': 'Select function...',
    'field.availability': 'Availability',
    'field.availabilityRanges': 'Availability Ranges',
    'field.addRange': 'Add Range',
    'field.range': 'Range',
    'field.noRanges': 'No availability ranges registered.',
    'field.clickAddRange': 'Click "Add Range" to define availability periods.',
    'field.startDate': 'Start Date',
    'field.endDate': 'End Date',
    'field.startTime': 'Start Time',
    'field.endTime': 'End Time',
    'field.weekDays': 'Week Days',
    'field.classification': 'Classification',
    'field.cityState': 'City/State',
    'field.fiscalId': 'Tax ID',
    'field.generalData': 'General Data',
    'field.workName': 'Stage Name',
    'field.workNamePlaceholder': 'Stage or working name',
    'field.document': 'ID/Document',
    'field.addAttachment': 'Add Attachment',
    'field.noAttachments': 'No attachments added',
    'field.attachmentsMaxSize': 'Attachments (max 2MB per file)',
    'field.addAbsencePeriod': 'Add Absence Period',
    'field.noAbsences': 'No absences registered',
    'field.absencesHint': 'Add vacation, day off, or leave periods',
    'field.absenceOverlapWarning': 'The system does not allow overlapping absence dates. Verify that the period does not conflict with existing absences.',
    'field.addSchedule': 'Add Schedule',
    'field.noSchedules': 'No schedules registered',
    'field.schedulesHint': 'Add work schedules with times and weekdays',
    'field.scheduleOverlapWarning': 'The system does not allow overlapping schedule periods.',
    'field.scaleMap': 'Schedule Map',
    'field.availabilityMap': 'Availability Map',
    'field.days': 'Days',
    'field.reason': 'Reason',
    'field.vacation': 'Vacation',
    'field.dayOff': 'Day Off',
    'field.maternityLeave': 'Maternity Leave',
    'field.paternityLeave': 'Paternity Leave',
    'field.externalCourse': 'External Course',
    'field.businessTrip': 'Business Trip',
    'field.selectDepartmentFirst': 'Select a department first',
    'field.noFunctionsRegistered': 'No functions registered',
    'field.overlapWarning': 'This range overlaps with another existing range.',
    'field.fillFieldsFor': 'Fill in fields to',
    'field.thePhysicalResource': 'the physical resource.',
    'field.services': 'Services',
    'field.files': 'Files',
    'field.fillSupplierData': 'Fill in supplier data.',
    'field.selectClassification': 'Select classification',
    'field.manageCollaborators': 'Manage organization collaborators',
    'field.noCollaboratorRegistered': 'No collaborators registered',
    'field.addCollaborator': 'Add Collaborator',
    'field.manageCollaboratorsTeam': 'Add collaborators to manage your team.',
    'field.managePhysicalResources': 'Manage physical resources (spaces, studios, etc.)',
    'field.noPhysicalResourceRegistered': 'No physical resources registered',
    'field.addPhysicalResource': 'Add Resource',
    'field.physicalResourcesHint': 'Add physical resources like studios and rooms.',
    'field.manageTechnicalResources': 'Manage available technical resources',
    'field.noTechnicalResourceRegistered': 'No technical resources registered',
    'field.addTechnicalResource': 'Add Resource',
    'field.technicalResourcesHint': 'Add technical resources for use in recordings.',
    'field.managePeople': 'Manage people registered in the system',
    'field.noPersonRegistered': 'No people registered',
    'field.addPerson': 'Add Person',
    'field.peopleHint': 'Add people to manage your registry.',
    'field.manageSuppliers': 'Manage service suppliers',
    'field.noSupplierRegistered': 'No suppliers registered',
    'field.addSupplier': 'Add Supplier',
    'field.suppliersHint': 'Add suppliers to manage partnerships.',
    'field.newResource': 'New Resource',
    'field.newPerson': 'New Person',
    'field.newSupplier': 'New Supplier',
    'field.editSupplier': 'Edit Supplier',
    'field.suppliers': 'Suppliers',
    'field.budget': 'Budget',
    'field.selectUnitFirst': 'Select a Unit first',
    'field.selectUnitToEnable': 'Select a Business Unit to enable',
    'field.budgetPlaceholder': 'Budget value',
    'field.recordings': 'Recordings',
    'field.cast': 'Cast',
    'field.costs': 'Costs',
    'field.noRecordings': 'No recordings associated.',
    'field.clickGenerate': 'Click "Generate" to create recordings automatically.',
    'field.noStatus': 'No status',
    'field.saveBeforeGenerating': 'Save the content before generating recordings.',
    'field.defineEpisodesFirst': 'Define the number of episodes before generating.',
    'field.allRecordingsGenerated': 'All recordings have already been generated for this content.',
    'field.recordingsGenerated': 'recordings generated successfully!',
    'field.descriptionRequired': 'Description is required.',
    'field.fillContentData': 'Fill in the fields to register the content.',
    'field.editContentData': 'Fill in the fields to edit the content.',
    'field.confirmDeleteContent': 'Do you really want to delete this content? All associated recordings will also be removed.',
    'field.contentDeleteBlocked': 'This content has recordings with associated resources, technicians, physical or third-party.',
    'field.contentDeleted': 'Content and associated recordings removed!',
    'field.contentUpdated': 'Content updated!',
    'field.contentCreated': 'Content registered!',
    'field.contentLoadError': 'Error loading content',
    'field.contentSaveError': 'Error saving content',
    'field.contentDeleteError': 'Error deleting content',
    'field.confirmDeleteSupplier': 'Do you really want to delete this supplier?',
    'field.supplierUpdated': 'Supplier updated!',
    'field.supplierCreated': 'Supplier registered!',
    'field.supplierDeleted': 'Supplier removed!',
    'field.supplierLoadError': 'Error loading suppliers',
    'field.supplierSaveError': 'Error saving supplier',
    'field.supplierDeleteError': 'Error deleting supplier',
    'field.sun': 'Sun',
    'field.mon': 'Mon',
    'field.tue': 'Tue',
    'field.wed': 'Wed',
    'field.thu': 'Thu',
    'field.fri': 'Fri',
    'field.sat': 'Sat',
    
    // Teams
    'teams.title': 'Teams',
    'teams.description': 'Manage human resources teams',
    'teams.new': 'New Team',
    'teams.edit': 'Edit Team',
    'teams.empty': 'No teams registered. Add a team.',
    'teams.created': 'Team created successfully!',
    'teams.updated': 'Team updated successfully!',
    'teams.deleted': 'Team removed successfully!',
    'teams.loadError': 'Error loading teams',
    'teams.saveError': 'Error saving team',
    'teams.deleteError': 'Error deleting team',
    'teams.members': 'Members',
    'teams.membersList': 'Team Members',
    'teams.addMember': 'Add Member',
    'teams.selectMember': 'Select a human resource.',
    'teams.selectMemberPlaceholder': 'Select a human resource...',
    'teams.saveFirst': 'Save the team before adding members.',
    'teams.memberAdded': 'Member added successfully!',
    'teams.memberRemoved': 'Member removed successfully!',
    'teams.memberAddError': 'Error adding member.',
    'teams.memberRemoveError': 'Error removing member.',
    'teams.memberNotFound': 'Resource not found',
    'teams.noMembers': 'No members in the team.',
    'teams.addMemberHint': 'Click "Add Member" to include.',
    'teams.newDescription': 'Register new team.',
    'teams.editDescription': 'Edit team.',
    'teams.function': 'Function',

    // Currency
    'currency.symbol': '$',
    'currency.code': 'USD',
  },
  es: {
    // Login
    'login.welcome': 'Bienvenido a Kreato',
    'login.subtitle': 'Sistema de Gestión de Producción',
    'login.user': 'Usuario',
    'login.user.placeholder': 'Ingrese su usuario',
    'login.password': 'Contraseña',
    'login.password.placeholder': 'Ingrese su contraseña',
    'login.submit': 'Iniciar Sesión',
    'login.loading': 'Iniciando...',
    'login.error': 'Usuario o contraseña inválidos',
    'login.hint': 'Acceso inicial: Admin / kreato',
    
    // Common
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.add': 'Agregar',
    'common.new': 'Nuevo',
    'common.search': 'Buscar...',
    'common.actions': 'Acciones',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.loading': 'Cargando...',
    'common.success': 'Éxito',
    'common.error': 'Error',
    'common.deleted': 'Eliminado',
    'common.confirm.delete': '¿Realmente desea eliminar?',
    'common.noResults': 'No se encontraron resultados',
    'common.code': 'Código',
    'common.externalCode': 'Código Externo',
    'common.name': 'Nombre',
    'common.description': 'Descripción',
    'common.status': 'Estado',
    'common.date': 'Fecha',
    'common.user': 'Usuario',
    'common.registrationDate': 'Fecha de Registro',
    'common.registrationUser': 'Registrado Por',
    'common.total': 'Total',
    'common.quantity': 'Cantidad',
    'common.value': 'Valor',
    'common.observations': 'Observaciones',
    'common.image': 'Imagen',
    'common.logo': 'Logotipo',
    'common.upload': 'Subir',
    'common.change': 'Cambiar',
    'common.remove': 'Eliminar',
    'common.select': 'Seleccione...',
    'common.none': 'Ninguno',
    'common.active': 'Activo',
    'common.inactive': 'Inactivo',
    'common.generate': 'Generar',
    'common.generating': 'Generando...',
    'common.registered': 'Registrados',
    'common.activeNow': 'activas ahora',
    'common.inSystem': 'Registrados en el sistema',
    'common.activeCollaborators': 'Colaboradores activos',
    'common.registeredEquipment': 'Equipos registrados',
    'common.locationsSpaces': 'Ubicaciones/espacios',
    'common.registeredPartners': 'Socios registrados',
    'common.allocatedResources': 'recurso(s) asignado(s)',
    'common.color': 'Color',
    'common.type': 'Tipo',
    'common.category': 'Categoría',
    'common.phone': 'Teléfono',
    'common.email': 'Correo',
    'common.address': 'Dirección',
    'common.city': 'Ciudad',
    'common.state': 'Estado',
    'common.zip': 'Código Postal',
    'common.country': 'País',
    'common.notes': 'Notas',
    'common.details': 'Detalles',
    'common.info': 'Información',
    'common.general': 'General',
    'common.all': 'Todos',
    'common.filter': 'Filtrar',
    'common.clear': 'Limpiar',
    'common.apply': 'Aplicar',
    'common.close': 'Cerrar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.finish': 'Finalizar',
    'common.continue': 'Continuar',
    'common.confirm': 'Confirmar',
    'common.update': 'Actualizar',
    'common.create': 'Crear',
    'common.view': 'Ver',
    'common.download': 'Descargar',
    'common.export': 'Exportar',
    'common.import': 'Importar',
    'common.print': 'Imprimir',
    'common.copy': 'Copiar',
    'common.paste': 'Pegar',
    'common.cut': 'Cortar',
    'common.undo': 'Deshacer',
    'common.redo': 'Rehacer',
    'common.refresh': 'Actualizar',
    'common.reload': 'Recargar',
    'common.reset': 'Restablecer',
    'common.start': 'Iniciar',
    'common.stop': 'Detener',
    'common.pause': 'Pausar',
    'common.resume': 'Reanudar',
    'common.send': 'Enviar',
    'common.receive': 'Recibir',
    'common.upload.formats': 'Formatos: JPG, PNG, GIF. Máx: 2MB',
    'common.clickToAdd': 'Haga clic para agregar',
    'common.maxChars': 'Máx 10 caracteres',
    'common.required': 'Campo obligatorio',
    'common.startTime': 'Hora Inicio',
    'common.endTime': 'Hora Fin',
    
    // Theme
    'theme.dark': 'Tema Oscuro',
    'theme.light': 'Tema Claro',
    'settings': 'Configuración',
    'language': 'Idioma',
    
    // Menu / Sidebar
    'menu.dashboard': 'Panel',
    'menu.production': 'Producción',
    'menu.content': 'Contenido',
    'menu.recordings': 'Grabaciones',
    'menu.maps': 'Mapas',
    'menu.resources': 'Recursos',
    'menu.people': 'Personas',
    'menu.humanResources': 'Recursos Humanos',
    'menu.technicalResources': 'Recursos Técnicos',
    'menu.physicalResources': 'Recursos Físicos',
    'menu.suppliers': 'Proveedores',
    'menu.services': 'Servicios',
    'menu.costumes': 'Vestuarios',
    'menu.admin': 'Administración',
    'menu.users': 'Usuarios',
    'menu.accessProfiles': 'Perfil de Acceso',
    'menu.businessUnits': 'Unidad de Negocio',
    'menu.profitCenters': 'Centro de Beneficio',
    'menu.forms': 'Formularios',
    'menu.parameters': 'Parámetros',
    'menu.logout': 'Salir',
    'menu.recordingTypes': 'Tipos de Grabación',
    'menu.classification': 'Clasificación',
    'menu.recordingStatus': 'Estado de Grabación',
    'menu.positions': 'Cargos',
    'menu.departments': 'Departamentos',
    'menu.functions': 'Funciones',
    'menu.supplierCategory': 'Categorías de Proveedores',
    'menu.peopleClassification': 'Clasificación de Personas',
    'menu.costumeType': 'Tipo de Vestuario',
    'menu.material': 'Material',
    'menu.teams': 'Equipos',
    'menu.tasks': 'Tareas',
    'menu.taskStatus': 'Estado de Tarea',
    'menu.priceTables': 'Tablas de Precios',
    
    // Tasks
    'tasks.title': 'Tareas',
    'tasks.description': 'Gestione las tareas de producción',
    'tasks.new': 'Nueva Tarea',
    'tasks.edit': 'Editar Tarea',
    'tasks.total': 'Total de Tareas',
    'tasks.pending': 'Pendientes',
    'tasks.inProgress': 'En Progreso',
    'tasks.completed': 'Completadas',
    'tasks.empty': 'No hay tareas registradas',
    'tasks.addFirst': 'Agregar primera tarea',
    'tasks.created': '¡Tarea creada con éxito!',
    'tasks.updated': '¡Tarea actualizada con éxito!',
    'tasks.taskTitle': 'Título de la Tarea',
    'tasks.taskTitlePlaceholder': 'Ingrese el título de la tarea',
    'tasks.taskDescription': 'Descripción',
    'tasks.taskDescriptionPlaceholder': 'Describa la tarea',
    'tasks.recording': 'Grabación',
    'tasks.status': 'Estado',
    'tasks.assignee': 'Responsable',
    'tasks.priority': 'Prioridad',
    'tasks.priorityLow': 'Baja',
    'tasks.priorityMedium': 'Media',
    'tasks.priorityHigh': 'Alta',
    'tasks.startDate': 'Fecha de Inicio',
    'tasks.dueDate': 'Fecha Límite',
    'tasks.formDescription': 'Complete los datos de la tarea',
    'tasks.deleteConfirmation': 'Esta acción no se puede deshacer.',
    'tasks.filterByStatus': 'Filtrar por estado',
    'tasks.filterByRecording': 'Filtrar por grabación',
    
    // Dashboard
    'dashboard.title': 'Panel',
    'dashboard.hello': 'Hola',
    'dashboard.welcome': 'Bienvenido al panel de control de Kreato',
    'dashboard.overview': 'Resumen',
    'dashboard.recordings': 'Grabaciones',
    'dashboard.contents': 'Contenidos',
    'dashboard.humanResources': 'Recursos Humanos',
    'dashboard.businessUnits': 'Unidades de Negocio',
    'dashboard.technicalResources': 'Recursos Técnicos',
    'dashboard.physicalResources': 'Recursos Físicos',
    'dashboard.suppliers': 'Proveedores',
    'dashboard.upcomingRecordings': 'Próximas Grabaciones',
    'dashboard.recordingsThisWeek': 'Grabaciones con recursos asignados esta semana',
    'dashboard.noRecordingsThisWeek': 'No hay grabaciones con recursos asignados esta semana',
    'dashboard.systemSummary': 'Resumen del Sistema',
    'dashboard.registryOverview': 'Visión general de registros',
    'dashboard.totalRecordings': 'Total de Grabaciones',
    'dashboard.totalContents': 'Total de Contenidos',
    
    // Business Units
    'businessUnits.title': 'Unidades de Negocio',
    'businessUnits.description': 'Gestione las unidades de negocio de la organización',
    'businessUnits.new': 'Nueva Unidad de Negocio',
    'businessUnits.edit': 'Editar Unidad de Negocio',
    'businessUnits.empty': 'No hay unidades de negocio registradas',
    'businessUnits.emptyDescription': 'Comience agregando unidades de negocio para organizar su sistema.',
    'businessUnits.deleted': '¡Unidad de Negocio eliminada con éxito!',
    'businessUnits.saved': '¡Unidad de Negocio guardada con éxito!',
    'businessUnits.updated': '¡Unidad de Negocio actualizada con éxito!',
    
    // Profit Centers
    'profitCenters.title': 'Centros de Beneficio',
    'profitCenters.description': 'Gestione los centros de beneficio de la organización',
    'profitCenters.new': 'Nuevo Centro de Beneficio',
    'profitCenters.edit': 'Editar Centro de Beneficio',
    
    // Users
    'users.title': 'Usuarios',
    'users.description': 'Gestione los usuarios del sistema',
    'users.new': 'Nuevo Usuario',
    'users.edit': 'Editar Usuario',
    
    // Access Profiles
    'accessProfiles.title': 'Perfiles de Acceso',
    'accessProfiles.description': 'Gestione los perfiles de acceso del sistema',
    'accessProfiles.new': 'Nuevo Perfil de Acceso',
    'accessProfiles.edit': 'Editar Perfil de Acceso',
    
    // Content
    'content.title': 'Contenido',
    'content.description': 'Gestione los contenidos de producción',
    'content.new': 'Nuevo Contenido',
    'content.edit': 'Editar Contenido',
    'content.episodes': 'Cant. Episodios',
    'content.synopsis': 'Descripción / Sinopsis',
    'content.productionYear': 'Año de Producción',
    'content.contentType': 'Tipo de Contenido',
    'content.classification': 'Clasificación',
    'content.empty': 'No hay contenido registrado',
    'content.emptyDescription': 'Comience agregando contenido para organizar su producción.',
    'content.noRecordings': 'No hay grabaciones asociadas.',
    'content.clickGenerate': 'Haga clic en "Generar" para crear las grabaciones automáticamente.',
    'content.contentRecordings': 'Grabaciones del Contenido',
    
    // Recordings
    'recordings.title': 'Grabaciones',
    'recordings.description': 'Gestione las grabaciones de producción',
    'recordings.new': 'Nueva Grabación',
    'recordings.edit': 'Editar Grabación',
    'recordings.expectedDate': 'Fecha Prevista',
    'recordings.generalData': 'Datos Generales',
    'recordings.resources': 'Recursos',
    'recordings.cast': 'Elenco',
    'recordings.guests': 'Invitados',
    'recordings.costumes': 'Vestuarios',
    'recordings.thirdParties': 'Terceros',
    'recordings.costs': 'Costos',
    'recordings.empty': 'No hay grabaciones registradas',
    'recordings.emptyDescription': 'Comience agregando grabaciones para gestionar su producción.',
    'recordings.businessUnit': 'Unidad de Negocio',
    'recordings.profitCenter': 'Centro de Beneficio',
    
    // Cast
    'cast.title': 'Elenco',
    'cast.add': 'Agregar al Elenco',
    'cast.person': 'Persona',
    'cast.character': 'Personaje',
    'cast.characterDescription': 'Descripción del Personaje',
    'cast.costumes': 'Vestuarios del Personaje',
    'cast.actor': 'Actor/Actriz',
    'cast.empty': 'Ningún miembro del elenco agregado',
    'cast.total': 'miembro(s) del elenco',
    
    // Guests
    'guests.title': 'Invitados',
    'guests.add': 'Agregar Invitado',
    'guests.roleInRecording': 'Función en la Grabación',
    'guests.contact': 'Contacto',
    'guests.empty': 'Ningún invitado agregado',
    'guests.total': 'invitado(s)',
    
    // Costumes
    'costumes.title': 'Vestuarios',
    'costumes.description': 'Gestione los vestuarios disponibles',
    'costumes.new': 'Nuevo Vestuario',
    'costumes.edit': 'Editar Vestuario',
    'costumes.code': 'Código del Vestuario',
    'costumes.type': 'Tipo de Vestuario',
    'costumes.size': 'Tamaño',
    'costumes.primaryColor': 'Color Predominante',
    'costumes.secondaryColor': 'Color Secundario',
    'costumes.material': 'Material',
    'costumes.images': 'Imágenes',
    'costumes.mainImage': 'Imagen Principal',
    'costumes.empty': 'No hay vestuarios registrados',
    'costumes.emptyDescription': 'Comience agregando vestuarios para su producción.',
    'costumes.addToCostume': 'Agregar Vestuario',
    'costumes.noCostumesAdded': 'No hay vestuarios agregados a esta grabación',
    
    // People
    'people.title': 'Personas',
    'people.description': 'Gestione el registro de personas',
    'people.new': 'Nueva Persona',
    'people.edit': 'Editar Persona',
    'people.firstName': 'Nombre',
    'people.lastName': 'Apellido',
    'people.workName': 'Nombre Artístico',
    'people.phone': 'Teléfono',
    'people.email': 'Correo',
    'people.photo': 'Foto',
    'people.empty': 'No hay personas registradas',
    'people.emptyDescription': 'Comience agregando personas al sistema.',
    
    // Human Resources
    'humanResources.title': 'Recursos Humanos',
    'humanResources.description': 'Gestione los recursos humanos disponibles',
    'humanResources.new': 'Nuevo Recurso Humano',
    'humanResources.edit': 'Editar Recurso Humano',
    'humanResources.empty': 'No hay recursos humanos registrados',
    
    // Technical Resources
    'technicalResources.title': 'Recursos Técnicos',
    'technicalResources.description': 'Gestione los recursos técnicos disponibles',
    'technicalResources.new': 'Nuevo Recurso Técnico',
    'technicalResources.edit': 'Editar Recurso Técnico',
    'technicalResources.empty': 'No hay recursos técnicos registrados',
    
    // Physical Resources
    'physicalResources.title': 'Recursos Físicos',
    'physicalResources.description': 'Gestione los recursos físicos disponibles',
    'physicalResources.new': 'Nuevo Recurso Físico',
    'physicalResources.edit': 'Editar Recurso Físico',
    'physicalResources.empty': 'No hay recursos físicos registrados',
    
    // Suppliers
    'suppliers.title': 'Proveedores',
    'suppliers.description': 'Gestione los proveedores',
    'suppliers.new': 'Nuevo Proveedor',
    'suppliers.edit': 'Editar Proveedor',
    'suppliers.empty': 'No hay proveedores registrados',
    
    // Services
    'services.title': 'Servicios',
    'services.description': 'Gestione los servicios disponibles',
    'services.new': 'Nuevo Servicio',
    'services.edit': 'Editar Servicio',
    'services.empty': 'No hay servicios registrados',
    
    // Maps
    'maps.title': 'Mapas',
    'maps.description': 'Visualice los mapas de producción',
    'maps.physicalResources': 'Recursos Físicos',
    'maps.humanResources': 'Recursos Humanos',
    'maps.costAppropriation': 'Apropiación de Costos',
    
    // Parameters
    'parameters.positions': 'Cargos',
    'parameters.departments': 'Departamentos',
    'parameters.functions': 'Funciones',
    'parameters.supplierCategories': 'Categorías de Proveedores',
    'parameters.peopleClassification': 'Clasificación de Personas',
    'parameters.costumeTypes': 'Tipos de Vestuario',
    'parameters.materials': 'Materiales',
    'parameters.recordingTypes': 'Tipos de Grabación',
    'parameters.recordingStatus': 'Estado de Grabación',
    'parameters.classification': 'Clasificación',
    
    // Costs
    'costs.title': 'Costos',
    'costs.estimatedCost': 'Costo Estimado',
    'costs.actualCost': 'Costo Real',
    'costs.dailyRate': 'Tarifa Diaria',
    'costs.hourlyRate': 'Tarifa por Hora',
    'costs.totalCost': 'Costo Total',
    
    // Third Parties
    'thirdParties.title': 'Terceros',
    'thirdParties.add': 'Agregar Tercero',
    'thirdParties.empty': 'No hay terceros agregados',
    
    // Resources Tab
    'resourcesTab.allocate': 'Asignar Recurso',
    'resourcesTab.startDate': 'Fecha Inicio',
    'resourcesTab.endDate': 'Fecha Fin',
    'resourcesTab.noResourcesAllocated': 'No hay recursos asignados',
    
    // Script/Roteiro
    'script.title': 'Guión de Grabación',
    'script.description': 'Organice el orden de las escenas a grabar',
    'script.addScene': 'Agregar Escena',
    'script.noScenes': 'No hay escenas registradas',
    'script.addFirstScene': 'Agregar primera escena',
    'script.sceneAdded': '¡Escena agregada con éxito!',
    'script.sceneRemoved': '¡Escena eliminada con éxito!',
    'script.chapter': 'Capítulo',
    'script.sceneNumber': 'Número de Escena',
    'script.environment': 'Ambiente',
    'script.environmentType': 'Tipo de Ambiente',
    'script.period': 'Período',
    'script.rhythm': 'Ritmo',
    'script.recordingLocation': 'Lugar de Grabación',
    'script.approximateTime': 'Tiempo Aproximado',
    'script.charactersInScene': 'Personajes en Escena (del Elenco)',
    'script.noCast': 'No hay elenco registrado. Agregue miembros al elenco en la pestaña "Elenco".',
    'script.extras': 'Figurantes (Personas clasificadas como Figurante)',
    'script.noExtras': 'No hay persona clasificada como "Figurante". Registre personas en Recursos > Personas.',
    'script.sceneDescription': 'Descripción de la Escena',
    'script.formatHint': 'Use marcadores de texto: *texto* para cursiva, **texto** para negrita',
    'script.external': 'Externo',
    'script.internal': 'Interno',
    'script.day': 'Día',
    'script.night': 'Noche',
    'script.morning': 'Mañana',
    'script.afternoon': 'Tarde',
    'script.dawn': 'Madrugada',
    'script.dramatic': 'Dramático',
    'script.fastScene': 'Escena Rápida',
    'script.contemplative': 'Contemplativa',
    'script.scene': 'Escena',
    'script.selectCharacters': 'Seleccionar Personajes',
    'script.searchCharacter': 'Buscar personaje...',
    'script.selectExtras': 'Seleccionar Figurantes',
    'script.searchExtra': 'Buscar figurante...',
    'script.exportPDF': 'Exportar PDF',
    'script.exportSuccess': '¡Guión exportado con éxito!',
    'script.noScenesToExport': 'No hay escenas para exportar',
    'common.of': 'de',
    
    // Costs Tab
    'costsTab.noCosts': 'Sin costos estimados',
    'costsTab.noCostsDescription': 'Asigne recursos con horarios definidos en la pestaña "Recursos" para ver los costos estimados.',
    'costsTab.totalHours': 'Total de Horas',
    'costsTab.estimatedHours': 'Horas estimadas de trabajo',
    'costsTab.totalCost': 'Costo Total',
    'costsTab.estimatedCost': 'Costo estimado de grabación',
    'costsTab.costItems': 'Ítems de Costo',
    'costsTab.allocatedWithCost': 'Recursos asignados con costo',
    'costsTab.humanResources': 'Recursos Humanos',
    'costsTab.physicalResources': 'Recursos Físicos',
    'costsTab.resource': 'Recurso',
    'costsTab.hours': 'Horas',
    'costsTab.hourlyRate': 'Costo/Hora',
    'costsTab.daysOccupation': 'día(s) de ocupación',
    'costsTab.daysIn': 'día(s) en',
    'costsTab.subtotal': 'Subtotal',
    'costsTab.totalEstimatedCost': 'Costo Total Estimado',
    'costsTab.workHours': 'horas de trabajo',
    // Fields / Columns / Modals
    'field.department': 'Departamento',
    'field.function': 'Función',
    'field.costPerHour': 'Costo/Hora',
    'field.stock': 'Inventario',
    'field.photo': 'Foto',
    'field.lastName': 'Apellido',
    'field.gender': 'Sexo',
    'field.male': 'Masculino',
    'field.female': 'Femenino',
    'field.other': 'Otro',
    'field.birthDate': 'Fecha de Nacimiento',
    'field.hireDate': 'Fecha de Contratación',
    'field.personalData': 'Datos Personales',
    'field.absences': 'Ausencias',
    'field.schedules': 'Escalas',
    'field.attachments': 'Anexos',
    'field.collaborator': 'Colaborador',
    'field.newCollaborator': 'Nuevo Colaborador',
    'field.editCollaborator': 'Editar Colaborador',
    'field.fillCollaboratorData': 'Complete los datos del colaborador.',
    'field.operatorFunction': 'Función del Operador',
    'field.operatorFunctionHint': 'Define qué función puede operar este recurso',
    'field.selectFunction': 'Seleccione la función...',
    'field.availability': 'Disponibilidad',
    'field.availabilityRanges': 'Rangos de Disponibilidad',
    'field.addRange': 'Agregar Rango',
    'field.range': 'Rango',
    'field.noRanges': 'No hay rangos de disponibilidad registrados.',
    'field.clickAddRange': 'Haga clic en "Agregar Rango" para definir períodos de disponibilidad.',
    'field.startDate': 'Fecha Inicio',
    'field.endDate': 'Fecha Fin',
    'field.startTime': 'Hora Inicio',
    'field.endTime': 'Hora Fin',
    'field.weekDays': 'Días de la Semana',
    'field.classification': 'Clasificación',
    'field.cityState': 'Ciudad/Estado',
    'field.fiscalId': 'Identificación Fiscal',
    'field.generalData': 'Datos Generales',
    'field.workName': 'Nombre Artístico',
    'field.workNamePlaceholder': 'Nombre artístico o de trabajo',
    'field.document': 'RUT/Documento',
    'field.addAttachment': 'Agregar Anexo',
    'field.noAttachments': 'Ningún anexo agregado',
    'field.attachmentsMaxSize': 'Anexos (máx. 2MB por archivo)',
    'field.addAbsencePeriod': 'Agregar Período de Ausencia',
    'field.noAbsences': 'Ninguna ausencia registrada',
    'field.absencesHint': 'Agregue períodos de vacaciones, descansos o licencias',
    'field.absenceOverlapWarning': 'El sistema no permite registrar ausencias con fechas superpuestas. Verifique que el período no conflicte con ausencias existentes.',
    'field.addSchedule': 'Agregar Escala',
    'field.noSchedules': 'Ninguna escala registrada',
    'field.schedulesHint': 'Agregue escalas de trabajo con horarios y días de la semana',
    'field.scheduleOverlapWarning': 'El sistema no permite registrar escalas con períodos superpuestos.',
    'field.scaleMap': 'Mapa de Escalas',
    'field.availabilityMap': 'Mapa de Disponibilidad',
    'field.days': 'Días',
    'field.reason': 'Motivo',
    'field.vacation': 'Vacaciones',
    'field.dayOff': 'Descanso',
    'field.maternityLeave': 'Licencia de Maternidad',
    'field.paternityLeave': 'Licencia de Paternidad',
    'field.externalCourse': 'Curso Externo',
    'field.businessTrip': 'Viaje de Trabajo',
    'field.selectDepartmentFirst': 'Seleccione un departamento primero',
    'field.noFunctionsRegistered': 'Ninguna función registrada',
    'field.overlapWarning': 'Este rango se superpone con otro rango existente.',
    'field.fillFieldsFor': 'Complete los campos para',
    'field.thePhysicalResource': 'el recurso físico.',
    'field.services': 'Servicios',
    'field.files': 'Archivos',
    'field.fillSupplierData': 'Complete los datos del proveedor.',
    'field.selectClassification': 'Seleccione la clasificación',
    'field.manageCollaborators': 'Gestione los colaboradores de la organización',
    'field.noCollaboratorRegistered': 'Ningún colaborador registrado',
    'field.addCollaborator': 'Agregar Colaborador',
    'field.manageCollaboratorsTeam': 'Agregue colaboradores para gestionar su equipo.',
    'field.managePhysicalResources': 'Gestione los recursos físicos (espacios, estudios, etc.)',
    'field.noPhysicalResourceRegistered': 'Ningún recurso físico registrado',
    'field.addPhysicalResource': 'Agregar Recurso',
    'field.physicalResourcesHint': 'Agregue recursos físicos como estudios y salas.',
    'field.manageTechnicalResources': 'Gestione los recursos técnicos disponibles',
    'field.noTechnicalResourceRegistered': 'Ningún recurso técnico registrado',
    'field.addTechnicalResource': 'Agregar Recurso',
    'field.technicalResourcesHint': 'Agregue recursos técnicos para usar en grabaciones.',
    'field.managePeople': 'Gestione las personas registradas en el sistema',
    'field.noPersonRegistered': 'Ninguna persona registrada',
    'field.addPerson': 'Agregar Persona',
    'field.peopleHint': 'Agregue personas para gestionar su registro.',
    'field.manageSuppliers': 'Gestione los proveedores de servicios',
    'field.noSupplierRegistered': 'Ningún proveedor registrado',
    'field.addSupplier': 'Agregar Proveedor',
    'field.suppliersHint': 'Agregue proveedores para gestionar alianzas.',
    'field.newResource': 'Nuevo Recurso',
    'field.newPerson': 'Nueva Persona',
    'field.newSupplier': 'Nuevo Proveedor',
    'field.editSupplier': 'Editar Proveedor',
    'field.suppliers': 'Proveedores',
    'field.budget': 'Presupuesto',
    'field.selectUnitFirst': 'Seleccione una Unidad primero',
    'field.selectUnitToEnable': 'Seleccione una Unidad de Negocio para habilitar',
    'field.budgetPlaceholder': 'Valor del presupuesto',
    'field.recordings': 'Grabaciones',
    'field.cast': 'Elenco',
    'field.costs': 'Costos',
    'field.noRecordings': 'No hay grabaciones asociadas.',
    'field.clickGenerate': 'Haga clic en "Generar" para crear las grabaciones automáticamente.',
    'field.noStatus': 'Sin estado',
    'field.saveBeforeGenerating': 'Guarde el contenido antes de generar grabaciones.',
    'field.defineEpisodesFirst': 'Defina la cantidad de episodios antes de generar.',
    'field.allRecordingsGenerated': 'Todas las grabaciones ya fueron generadas para este contenido.',
    'field.recordingsGenerated': 'grabaciones generadas con éxito!',
    'field.descriptionRequired': 'La descripción es obligatoria.',
    'field.fillContentData': 'Complete los campos para registrar el contenido.',
    'field.editContentData': 'Complete los campos para editar el contenido.',
    'field.confirmDeleteContent': '¿Desea realmente eliminar este contenido? Todas las grabaciones asociadas también serán eliminadas.',
    'field.contentDeleteBlocked': 'Este contenido tiene grabaciones con recursos, técnicos, físicos o terceros asociados.',
    'field.contentDeleted': '¡Contenido y grabaciones asociadas eliminados!',
    'field.contentUpdated': '¡Contenido actualizado!',
    'field.contentCreated': '¡Contenido registrado!',
    'field.contentLoadError': 'Error al cargar contenidos',
    'field.contentSaveError': 'Error al guardar contenido',
    'field.contentDeleteError': 'Error al eliminar contenido',
    'field.confirmDeleteSupplier': '¿Desea realmente eliminar este proveedor?',
    'field.supplierUpdated': '¡Proveedor actualizado!',
    'field.supplierCreated': '¡Proveedor registrado!',
    'field.supplierDeleted': '¡Proveedor eliminado!',
    'field.supplierLoadError': 'Error al cargar proveedores',
    'field.supplierSaveError': 'Error al guardar proveedor',
    'field.supplierDeleteError': 'Error al eliminar proveedor',
    'field.sun': 'Dom',
    'field.mon': 'Lun',
    'field.tue': 'Mar',
    'field.wed': 'Mié',
    'field.thu': 'Jue',
    'field.fri': 'Vie',
    'field.sat': 'Sáb',
    
    // Teams
    'teams.title': 'Equipos',
    'teams.description': 'Gestione los equipos de recursos humanos',
    'teams.new': 'Nuevo Equipo',
    'teams.edit': 'Editar Equipo',
    'teams.empty': 'Ningún equipo registrado. Agregue un equipo.',
    'teams.created': '¡Equipo creado con éxito!',
    'teams.updated': '¡Equipo actualizado con éxito!',
    'teams.deleted': '¡Equipo eliminado con éxito!',
    'teams.loadError': 'Error al cargar equipos',
    'teams.saveError': 'Error al guardar equipo',
    'teams.deleteError': 'Error al eliminar equipo',
    'teams.members': 'Miembros',
    'teams.membersList': 'Miembros del Equipo',
    'teams.addMember': 'Agregar Miembro',
    'teams.selectMember': 'Seleccione un recurso humano.',
    'teams.selectMemberPlaceholder': 'Seleccione un recurso humano...',
    'teams.saveFirst': 'Guarde el equipo antes de agregar miembros.',
    'teams.memberAdded': '¡Miembro agregado con éxito!',
    'teams.memberRemoved': '¡Miembro eliminado con éxito!',
    'teams.memberAddError': 'Error al agregar miembro.',
    'teams.memberRemoveError': 'Error al eliminar miembro.',
    'teams.memberNotFound': 'Recurso no encontrado',
    'teams.noMembers': 'Ningún miembro en el equipo.',
    'teams.addMemberHint': 'Haga clic en "Agregar Miembro" para incluir.',
    'teams.newDescription': 'Registrar nuevo equipo.',
    'teams.editDescription': 'Editar equipo.',
    'teams.function': 'Función',

    // Currency
    'currency.symbol': '€',
    'currency.code': 'EUR',
  },
};

// Currency locale mapping
const currencyLocales: Record<Language, { locale: string; currency: string }> = {
  pt: { locale: 'pt-BR', currency: 'BRL' },
  en: { locale: 'en-US', currency: 'USD' },
  es: { locale: 'es-ES', currency: 'EUR' },
};

// Language labels
export const languageLabels: Record<Language, { name: string; flag: string }> = {
  pt: { name: 'Português', flag: '🇵🇹' },
  en: { name: 'English', flag: '🇺🇸' },
  es: { name: 'Español', flag: '🇪🇸' },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('kreato_language');
    return (stored as Language) || 'pt';
  });

  useEffect(() => {
    localStorage.setItem('kreato_language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const formatCurrency = (value: number): string => {
    const { locale, currency } = currencyLocales[language];
    return new Intl.NumberFormat(locale, {
      style: 'currency',
      currency,
    }).format(value);
  };

  const formatDate = (date: Date | string): string => {
    const { locale } = currencyLocales[language];
    const dateObj = typeof date === 'string' ? new Date(date) : date;
    return new Intl.DateTimeFormat(locale).format(dateObj);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, formatCurrency, formatDate }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
